-- The experimental-features switch. docs/project/experimental-features.md,
-- docs/plans/experimental-features-toggle.md.
--
-- Null is off and is the default, so **no row is touched by this migration** —
-- every reader is already off, because off is what the absence of a date means.
-- A `boolean not null default false` would not have rewritten the table either
-- (Postgres stores a constant default as metadata since 11), but it would have
-- put a value in every reader's row to mean "nobody ever asked them", and it
-- would have thrown away *when* the switch was flipped.
-- docs/project/sql.md § A nullable timestamp says more than a boolean.
--
-- Generated by `drizzle-kit generate --name=experimental_features` and read
-- before applying: one statement, and no re-emission of anything an earlier
-- hand-written migration had already done (which is what 0030 had to repair).
-- meta/0032_snapshot.json beside this file is kept as generated.

ALTER TABLE "spideryarn"."reader_profiles" ADD COLUMN "experimental_since" timestamp with time zone;
