CREATE TABLE "spideryarn"."feedback" (
	"id" text NOT NULL,
	"owner_id" uuid NOT NULL,
	"reporter_email" text NOT NULL,
	"steps" text,
	"expected" text,
	"actual" text,
	"consented" boolean NOT NULL,
	"route_kind" text NOT NULL,
	"slug" text,
	"build_commit" text,
	"environment" text NOT NULL,
	"request_vercel_id" text,
	"diagnostics" jsonb,
	"diagnostics_version" integer,
	"screenshot" "bytea",
	"mirrored_at" timestamp with time zone,
	"sentry_event_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "feedback_owner_id_id_pk" PRIMARY KEY("owner_id","id"),
	CONSTRAINT "feedback_id_format" CHECK ("spideryarn"."feedback"."id" ~ '^spya-[abcdefghjkmnpqrstuvwxyz][abcdefghjkmnpqrstuvwxyz023456789]{5}$'),
	CONSTRAINT "feedback_route_kind" CHECK ("spideryarn"."feedback"."route_kind" in ('library', 'read', 'add', 'add-upload', 'design', 'profile', 'admin', 'login', 'callback', 'unknown')),
	CONSTRAINT "feedback_environment" CHECK ("spideryarn"."feedback"."environment" in ('production', 'preview', 'development', 'test')),
	CONSTRAINT "feedback_steps_shape" CHECK ("spideryarn"."feedback"."steps" is null or (length(btrim("spideryarn"."feedback"."steps")) > 0 and length("spideryarn"."feedback"."steps") <= 4000)),
	CONSTRAINT "feedback_expected_shape" CHECK ("spideryarn"."feedback"."expected" is null or (length(btrim("spideryarn"."feedback"."expected")) > 0 and length("spideryarn"."feedback"."expected") <= 4000)),
	CONSTRAINT "feedback_actual_shape" CHECK ("spideryarn"."feedback"."actual" is null or (length(btrim("spideryarn"."feedback"."actual")) > 0 and length("spideryarn"."feedback"."actual") <= 4000)),
	CONSTRAINT "feedback_says_something" CHECK ("spideryarn"."feedback"."steps" is not null or "spideryarn"."feedback"."expected" is not null or "spideryarn"."feedback"."actual" is not null),
	CONSTRAINT "feedback_reporter_email" CHECK (length(btrim("spideryarn"."feedback"."reporter_email")) > 0),
	CONSTRAINT "feedback_diagnostics_consented" CHECK ("spideryarn"."feedback"."consented" or "spideryarn"."feedback"."diagnostics" is null),
	CONSTRAINT "feedback_diagnostics_version" CHECK (("spideryarn"."feedback"."diagnostics" is null) = ("spideryarn"."feedback"."diagnostics_version" is null)),
	CONSTRAINT "feedback_screenshot_size" CHECK ("spideryarn"."feedback"."screenshot" is null or octet_length("spideryarn"."feedback"."screenshot") <= 400000),
	CONSTRAINT "feedback_mirrored_pair" CHECK ("spideryarn"."feedback"."sentry_event_id" is null or "spideryarn"."feedback"."mirrored_at" is not null)
);
--> statement-breakpoint
CREATE INDEX "feedback_owner_created_idx" ON "spideryarn"."feedback" USING btree ("owner_id","created_at");