-- The pipeline step `toc` becomes `hierarchy`, in the constraints and in the rows.
-- docs/plans/260831ak-rename-the-toc-step-to-hierarchy-everywhere.md
--
-- Generated by drizzle-kit (the two CHECK statements), then the data movement was
-- inserted BETWEEN the drops and the re-adds. That order is the whole point:
-- Postgres validates a re-added CHECK against the rows already in the table, so
-- narrowing before the data moves fails with a 23514 — and it passes on an empty
-- local container and fails wherever there is history, which is a delayed fuse and
-- a false negative in one.
--
-- The filesystem store's copies of the same string move separately, in
-- scripts/migrate-fs-toc-to-hierarchy.ts: the `steps/<step>.running` markers, the
-- checkpoint namespace directories, `data/_jobs/*.json` and `data/_ai-calls.jsonl`.
ALTER TABLE "spideryarn"."checkpoints" DROP CONSTRAINT "checkpoints_namespace";--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" DROP CONSTRAINT "revision_step_runs_step";--> statement-breakpoint
-- **Refuse rather than rewrite a job somebody is in the middle of.**
--
-- `jobs.work_key` is a sha256 of the ordered step names and four other things
-- (`workKeyFor`, src/jobs.ts), one of which is `urlKey(url)` — normalisation this
-- migration cannot reproduce — so SQL cannot recompute the key after moving the
-- names, and the column is NOT NULL so it cannot be blanked either.
--
-- A stale key is not cosmetic. `enqueueOrGet` (src/store/pg-jobs.ts) compares it
-- when the active-slug index refuses a second insert, and `enqueue` treats
-- `sameWork: false` from a URL request as *different work on a taken slug* and
-- allocates the next slug suffix — so one re-submitted URL becomes two articles.
--
-- So the rule is drained-or-nothing, enforced here instead of remembered: block
-- new work, let the queues empty, then migrate, then deploy. This RAISE aborts
-- the whole transaction, so a refusal leaves the database exactly as it was and
-- the migration can simply be run again once the queue is clear.
DO $$
DECLARE stuck bigint;
BEGIN
  SELECT count(*) INTO stuck
    FROM "spideryarn"."jobs"
   WHERE status in ('queued', 'running')
     AND steps @> '[{"name":"toc"}]'::jsonb;
  IF stuck > 0 THEN
    RAISE EXCEPTION
      'migration 0041 refused: % queued/running job(s) still hold a "toc" step. Their work_key hashes the old step names and SQL cannot recompute it, so rewriting them behind it would let one re-submitted URL become two articles. Drain the queue (or cancel those jobs) and run this again.', stuck;
  END IF;
END $$;--> statement-breakpoint
UPDATE "spideryarn"."revision_step_runs" SET "step_name" = 'hierarchy' WHERE "step_name" = 'toc';--> statement-breakpoint
-- Both columns of the spend ledger, or one stage's cost history splits two ways
-- with nothing to announce it: `step_name` is the pipeline step and `purpose` is
-- the `Task` (src/models.ts), and the same call writes 'toc' into both.
UPDATE "spideryarn"."ai_calls" SET "step_name" = 'hierarchy' WHERE "step_name" = 'toc';--> statement-breakpoint
UPDATE "spideryarn"."ai_calls" SET "purpose" = 'hierarchy' WHERE "purpose" = 'toc';--> statement-breakpoint
-- Between its own DROP and ADD above/below, for the identical 23514 reason.
-- `namespace` is part of the primary key; nothing collides, because no
-- 'hierarchy-labels' row can exist yet.
UPDATE "spideryarn"."checkpoints" SET "namespace" = 'hierarchy-labels' WHERE "namespace" = 'toc-labels';--> statement-breakpoint
-- `jobs.steps` is a `JobStep[]` — its elements are OBJECTS, `{"name":"toc",…}`,
-- not bare strings. `steps @> '["toc"]'` therefore matches no row that has ever
-- existed, and a statement written that way runs, reports success and changes
-- nothing. `e->>'name'` reads the field; `WITH ORDINALITY` and `ORDER BY` are
-- what give the original order back, and for `steps` the order is the meaning.
-- docs/project/sql.md § Migrating data inside a JSONB column.
UPDATE "spideryarn"."jobs" SET "steps" = (
  SELECT jsonb_agg(CASE WHEN e->>'name' = 'toc'
                        THEN jsonb_set(e, '{name}', '"hierarchy"')
                        ELSE e END ORDER BY ord)
    FROM jsonb_array_elements("steps") WITH ORDINALITY AS t(e, ord)
) WHERE "steps" @> '[{"name":"toc"}]'::jsonb;--> statement-breakpoint
-- **The postcondition, because two of those four have no constraint to catch
-- them.** The re-added CHECKs below prove `revision_step_runs` and `checkpoints`
-- moved — they cannot be added while a 'toc' row remains. Nothing proves the
-- other two, and "matched nothing" and "worked" print the same tick.
DO $$
DECLARE left_behind bigint;
BEGIN
  SELECT (SELECT count(*) FROM "spideryarn"."ai_calls" WHERE "step_name" = 'toc')
       + (SELECT count(*) FROM "spideryarn"."ai_calls" WHERE "purpose" = 'toc')
       + (SELECT count(*) FROM "spideryarn"."jobs" WHERE "steps" @> '[{"name":"toc"}]'::jsonb)
    INTO left_behind;
  IF left_behind > 0 THEN
    RAISE EXCEPTION
      'migration 0041: % row(s) still say "toc" in ai_calls.step_name, ai_calls.purpose or jobs.steps after the rewrites — the statements above matched less than they should have.', left_behind;
  END IF;
END $$;--> statement-breakpoint
ALTER TABLE "spideryarn"."checkpoints" ADD CONSTRAINT "checkpoints_namespace" CHECK ("spideryarn"."checkpoints"."namespace" in ('hierarchy-labels','pdf-chunk'));--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" ADD CONSTRAINT "revision_step_runs_step" CHECK ("spideryarn"."revision_step_runs"."step_name" in ('fetch','extract','blocks','hierarchy','assets','arc','tweets','glossary','quotes','ideas','timeline','sketch'));
