ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_state" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_requested_url" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_final_url" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_host" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_words" integer;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_sent_words" integer;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_chunks" text[];--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_matched_by" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_unreadable_why" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_evidence_sha" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_selection_version" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_read_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD COLUMN "paper_passages" jsonb;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_state" CHECK ("spideryarn"."citation_investigations"."paper_state" is null or "spideryarn"."citation_investigations"."paper_state" in ('read', 'no-address', 'unreadable', 'not-the-full-text', 'not-confirmed', 'identity-conflict'));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_dated" CHECK (("spideryarn"."citation_investigations"."paper_state" is null) = ("spideryarn"."citation_investigations"."paper_read_at" is null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_address" CHECK (("spideryarn"."citation_investigations"."paper_state" is not null and "spideryarn"."citation_investigations"."paper_state" <> 'no-address') = ("spideryarn"."citation_investigations"."paper_requested_url" is not null) and ("spideryarn"."citation_investigations"."paper_requested_url" is not null) = ("spideryarn"."citation_investigations"."paper_host" is not null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_final_url" CHECK (coalesce("spideryarn"."citation_investigations"."paper_state" in ('read', 'not-the-full-text', 'not-confirmed'), false) = ("spideryarn"."citation_investigations"."paper_final_url" is not null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_read" CHECK (coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false) = ("spideryarn"."citation_investigations"."paper_words" is not null) and coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false) = ("spideryarn"."citation_investigations"."paper_sent_words" is not null) and coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false) = ("spideryarn"."citation_investigations"."paper_chunks" is not null) and coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false) = ("spideryarn"."citation_investigations"."paper_matched_by" is not null) and coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false) = ("spideryarn"."citation_investigations"."paper_evidence_sha" is not null) and coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false) = ("spideryarn"."citation_investigations"."paper_selection_version" is not null) and ("spideryarn"."citation_investigations"."paper_passages" is null or coalesce("spideryarn"."citation_investigations"."paper_state" = 'read', false)));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_read_values" CHECK (("spideryarn"."citation_investigations"."paper_matched_by" is null or "spideryarn"."citation_investigations"."paper_matched_by" in ('doi', 'arxiv', 'title-author')) and ("spideryarn"."citation_investigations"."paper_words" is null or ("spideryarn"."citation_investigations"."paper_words" >= 0 and "spideryarn"."citation_investigations"."paper_sent_words" >= 0 and "spideryarn"."citation_investigations"."paper_sent_words" <= "spideryarn"."citation_investigations"."paper_words")) and ("spideryarn"."citation_investigations"."paper_evidence_sha" is null or "spideryarn"."citation_investigations"."paper_evidence_sha" ~ '^[0-9a-f]{64}$') and ("spideryarn"."citation_investigations"."paper_passages" is null or (case when jsonb_typeof("spideryarn"."citation_investigations"."paper_passages") = 'array' then jsonb_array_length("spideryarn"."citation_investigations"."paper_passages") <= 3 else false end)));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_investigations" ADD CONSTRAINT "citation_investigations_paper_unreadable" CHECK (coalesce("spideryarn"."citation_investigations"."paper_state" = 'unreadable', false) = ("spideryarn"."citation_investigations"."paper_unreadable_why" is not null) and ("spideryarn"."citation_investigations"."paper_unreadable_why" is null or "spideryarn"."citation_investigations"."paper_unreadable_why" in ('invalid-url', 'blocked', 'refused', 'not-found', 'site-error', 'network', 'timeout', 'too-large', 'not-a-document', 'paywall-or-empty', 'scan', 'damaged')));