-- The guide: a sixth chat_threads.kind, a conversation about how to read this
-- piece, one per article like Learn's three.
-- docs/plans/261007j-the-guide-a-conversation-about-how-to-read-this.md.
--
-- Generated by drizzle-kit, with no hand edit below this comment. Additive: a
-- WIDENING of the CHECK, the safe direction (as 20261003184359_explore_thread_kind.sql
-- was) -- every existing row satisfies the wider one, so it is a drop and a
-- re-add with no data movement. The unique index needs no fold, because no row
-- has kind 'guide' until this migration allows one. chat_threads_origin_chat_only
-- already keeps an origin off a guide.
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_kind";--> statement-breakpoint
CREATE UNIQUE INDEX "chat_threads_one_guide" ON "spideryarn"."chat_threads" USING btree ("article_id") WHERE "spideryarn"."chat_threads"."kind" = 'guide';--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_kind" CHECK ("spideryarn"."chat_threads"."kind" in ('chat','learn','candidates','tutorial','explore','guide'));