ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_state" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_support" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_support_quote" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_paper_does" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_paper_does_quote" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_excerpt_words" integer;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_context_hash" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD COLUMN "lookup_evidence_hash" text;--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_state" CHECK ("spideryarn"."citation_finds"."lookup_state" is null or "spideryarn"."citation_finds"."lookup_state" in ('assessed', 'no-extract', 'not-identified', 'unreadable'));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_support" CHECK ("spideryarn"."citation_finds"."lookup_support" is null or "spideryarn"."citation_finds"."lookup_support" in ('supports', 'partly', 'not-in-extract'));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_hashes" CHECK (("spideryarn"."citation_finds"."lookup_state" is null) = ("spideryarn"."citation_finds"."lookup_context_hash" is null) and ("spideryarn"."citation_finds"."lookup_state" is null) = ("spideryarn"."citation_finds"."lookup_evidence_hash" is null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_assessed" CHECK (("spideryarn"."citation_finds"."lookup_state" is not distinct from 'assessed') = ("spideryarn"."citation_finds"."lookup_support" is not null) and ("spideryarn"."citation_finds"."lookup_state" is not distinct from 'assessed') = ("spideryarn"."citation_finds"."lookup_excerpt_words" is not null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_support_quote" CHECK (coalesce("spideryarn"."citation_finds"."lookup_support" in ('supports', 'partly'), false) = ("spideryarn"."citation_finds"."lookup_support_quote" is not null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_paper_does" CHECK (("spideryarn"."citation_finds"."lookup_paper_does" is null) = ("spideryarn"."citation_finds"."lookup_paper_does_quote" is null) and ("spideryarn"."citation_finds"."lookup_paper_does" is null or "spideryarn"."citation_finds"."lookup_support" is not null));--> statement-breakpoint
ALTER TABLE "spideryarn"."citation_finds" ADD CONSTRAINT "citation_finds_lookup_lengths" CHECK (coalesce(char_length("spideryarn"."citation_finds"."lookup_paper_does"), 0) <= 240 and coalesce(char_length("spideryarn"."citation_finds"."lookup_support_quote"), 0) <= 400 and coalesce(char_length("spideryarn"."citation_finds"."lookup_paper_does_quote"), 0) <= 400 and coalesce("spideryarn"."citation_finds"."lookup_excerpt_words", 0) >= 0);