-- Bibliography's stored names, `citations` → `bibliography`: the EXPAND half.
-- docs/plans/261009w-peer-review-becomes-sources-all-the-way-down.md § The
-- database, and § After GPT Sol's plan review (F1, F5, F8).
--
-- **Why not a rename in place, as drizzle/20261001224759_skim.sql did.**
-- `npm run deploy` applies migrations and then waits for Vercel, so for those
-- minutes (and for as long as it takes if the build then fails) production
-- runs the pre-rename code against this schema. That code names
-- `article_revisions.citations` and the step `citations`; a column renamed in
-- place would fail every read of every revision. So this migration only ADDS,
-- and keeps both spellings true whichever version writes:
--
-- 1. `article_revisions.bibliography`, a copy of `citations`, and a BEFORE
--    trigger (`article_revisions_mirror_renamed`) that keeps the pair equal:
--    on insert whichever is null takes the other; on update whichever changed
--    is copied to the other (`IS DISTINCT FROM`, so clearing to null mirrors
--    too), and if one statement changes both, the new column wins.
-- 2. `revision_step_runs`: the CHECK (generated above) admits both names; the
--    `citations` rows are COPIED as `bibliography` rows (the old rows stay);
--    and an AFTER trigger (`revision_step_runs_mirror_renamed`) mirrors every
--    insert, update and delete on one spelling onto the other, guarded by
--    `pg_trigger_depth()` so its own writes do not mirror back. A lease the
--    old code takes on `citations` is the new code's lease on `bibliography`.
-- 3. `chat_threads`: the two origin CHECKs (generated above) admit
--    `bibliography` beside `citations`. Rows are NOT rewritten: the new code
--    reads `citations` as `bibliography` (src/thread-origin.ts) and writes the
--    new word.
-- 4. `jobs.steps` / `jobs.reset` are NOT rewritten: the new code reads the old
--    step name through `RETIRED_STEPS` (src/step-order.ts), as it does Skim's.
--    `ai_calls` is append-only, read through `currentLedgerName`.
--
-- **The pairs are written so Stage 3 can add its own.** Each trigger function
-- holds every renamed pair in one place — `step_name_partner` a CASE, the
-- column trigger one IF per pair — and Stage 3's migration recreates the three
-- functions (`CREATE OR REPLACE`) with `debate`/`reception`,
-- `debate-claims`/`sources-claims` added; the column trigger is recreated with
-- its wider `UPDATE OF` list.
--
-- **Undone by the CONTRACT migration**, which is not in `drizzle/`: it is the
-- Overseer queue item plan 261009w files (scripts/overseer-queue.ts), safe only
-- once this deploy is live. It drops the column `citations`, both triggers and
-- the three functions; deletes the `citations` step runs and narrows the step
-- CHECK; rewrites `jobs.steps`, `jobs.reset` and the chat origins, then
-- narrows their CHECKs; and removes `legacyCitations` from src/db/schema.ts.
--
-- What is deliberately NOT changed: the prompt version tag `citations/6` (in
-- each list's `version` and in `revision_step_runs.prompt_version`; changing it
-- would mark every unchanged list outdated), `jobs.work_key` (a hash SQL
-- cannot recompute; at worst one duplicate run across the window), and
-- `feedback` rows (evidence, kept as sent).
--
-- ---------------------------------------------- generated by drizzle-kit --
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_origin_mode";--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_origin_item";--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" DROP CONSTRAINT "revision_step_runs_step";--> statement-breakpoint
ALTER TABLE "spideryarn"."article_revisions" ADD COLUMN "bibliography" jsonb;--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_origin_mode" CHECK ("spideryarn"."chat_threads"."origin_mode" is null or "spideryarn"."chat_threads"."origin_mode" in ('debate','summary','glossary','citations','bibliography','ideas'));--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_origin_item" CHECK ("spideryarn"."chat_threads"."origin_mode" is null or "spideryarn"."chat_threads"."origin_mode" not in ('glossary','citations','bibliography','ideas') or ("spideryarn"."chat_threads"."origin_item_id" is not null and "spideryarn"."chat_threads"."origin_quote" is not null and "spideryarn"."chat_threads"."origin_block_id" is null and "spideryarn"."chat_threads"."origin_lens" is null));--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" ADD CONSTRAINT "revision_step_runs_step" CHECK ("spideryarn"."revision_step_runs"."step_name" in ('fetch','metadata','extract','blocks','structure','labels','assets','arc','tweets','glossary','quotes','skim','ideas','timeline','quiz','faq','relations','sketch','illustrated','debate','debate-claims','citations','bibliography','crossrefs','simple'));--> statement-breakpoint

-- ------------------------------------------------------ written by hand --

-- 1. The column pair. The copy first, then the trigger, so the copy is the
--    only writer of `bibliography` until the trigger takes over.
UPDATE "spideryarn"."article_revisions" SET "bibliography" = "citations" WHERE "citations" IS NOT NULL;--> statement-breakpoint

CREATE OR REPLACE FUNCTION "spideryarn"."article_revisions_mirror_renamed"()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  -- One block per renamed column, the new name first. On insert, whichever is
  -- null takes the other (both set: the new one wins); on update, whichever
  -- changed is copied over the other, and the new one wins a tie.
  IF TG_OP = 'INSERT' THEN
    IF NEW."bibliography" IS NOT NULL THEN
      NEW."citations" := NEW."bibliography";
    ELSE
      NEW."bibliography" := NEW."citations";
    END IF;
  ELSE
    IF NEW."bibliography" IS DISTINCT FROM OLD."bibliography" THEN
      NEW."citations" := NEW."bibliography";
    ELSIF NEW."citations" IS DISTINCT FROM OLD."citations" THEN
      NEW."bibliography" := NEW."citations";
    END IF;
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint

-- `UPDATE OF` the renamed columns, so an update that names neither (most of
-- them: every other step's column) pays nothing. `DROP … IF EXISTS` first
-- rather than `CREATE OR REPLACE TRIGGER`, the choice
-- drizzle/20260907200800_ingest_events_unlink_atomically.sql made.
DROP TRIGGER IF EXISTS "article_revisions_mirror_renamed" ON "spideryarn"."article_revisions";--> statement-breakpoint
CREATE TRIGGER "article_revisions_mirror_renamed"
  BEFORE INSERT OR UPDATE OF "citations", "bibliography" ON "spideryarn"."article_revisions"
  FOR EACH ROW EXECUTE FUNCTION "spideryarn"."article_revisions_mirror_renamed"();--> statement-breakpoint

-- 2. The step runs. Copied before the trigger exists, for the same reason.
--    `ON CONFLICT DO NOTHING` because a revision cannot have a `bibliography`
--    row yet (nothing wrote that name before this migration), so a conflict
--    would be news, not something to overwrite.
INSERT INTO "spideryarn"."revision_step_runs"
  ("revision_id", "step_name", "input_hash", "implementation_version", "prompt_version",
   "model", "status", "started_at", "finished_at", "attempt_id")
SELECT "revision_id", 'bibliography', "input_hash", "implementation_version", "prompt_version",
       "model", "status", "started_at", "finished_at", "attempt_id"
  FROM "spideryarn"."revision_step_runs"
 WHERE "step_name" = 'citations'
ON CONFLICT ("revision_id", "step_name") DO NOTHING;--> statement-breakpoint

-- Each renamed step name's other spelling, or null. The one list of pairs the
-- step-run trigger reads; Stage 3 recreates it with its own pairs.
CREATE OR REPLACE FUNCTION "spideryarn"."step_name_partner"("name" text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE "name"
    WHEN 'citations' THEN 'bibliography'
    WHEN 'bibliography' THEN 'citations'
    ELSE NULL
  END
$$;--> statement-breakpoint

-- AFTER, per row. The partner row is replaced wholesale (delete, then insert
-- NEW with the partner's name), not upserted column by column, so a column
-- added to this table later is mirrored without anybody editing this
-- function. `pg_trigger_depth() > 1` is this trigger's own writes coming back
-- round, and a cascade from `article_revisions` (which deletes both spellings
-- anyway): neither is mirrored.
--
-- What the old code relies on is kept: an `UPDATE` it issues still reports its
-- own row count (a trigger's writes are not counted), so `finishStepRun`'s
-- `rowCount !== 1` fence still holds.
CREATE OR REPLACE FUNCTION "spideryarn"."revision_step_runs_mirror_renamed"()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  partner text;
BEGIN
  IF pg_trigger_depth() > 1 THEN
    RETURN NULL;
  END IF;
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    partner := "spideryarn"."step_name_partner"(OLD."step_name");
    IF partner IS NOT NULL THEN
      DELETE FROM "spideryarn"."revision_step_runs"
       WHERE "revision_id" = OLD."revision_id" AND "step_name" = partner;
    END IF;
  END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    partner := "spideryarn"."step_name_partner"(NEW."step_name");
    IF partner IS NOT NULL THEN
      DELETE FROM "spideryarn"."revision_step_runs"
       WHERE "revision_id" = NEW."revision_id" AND "step_name" = partner;
      INSERT INTO "spideryarn"."revision_step_runs"
      SELECT (jsonb_populate_record(NEW, jsonb_build_object('step_name', partner))).*;
    END IF;
  END IF;
  RETURN NULL;
END;
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS "revision_step_runs_mirror_renamed" ON "spideryarn"."revision_step_runs";--> statement-breakpoint
CREATE TRIGGER "revision_step_runs_mirror_renamed"
  AFTER INSERT OR UPDATE OR DELETE ON "spideryarn"."revision_step_runs"
  FOR EACH ROW EXECUTE FUNCTION "spideryarn"."revision_step_runs_mirror_renamed"();--> statement-breakpoint

-- **The postcondition**, because a copy that matched nothing and one that
-- worked print the same tick: every `citations` run has its twin, and every
-- revision's pair agrees.
DO $$
DECLARE missing bigint;
DECLARE unequal bigint;
BEGIN
  SELECT count(*) INTO missing
    FROM "spideryarn"."revision_step_runs" o
   WHERE o."step_name" = 'citations'
     AND NOT EXISTS (SELECT 1 FROM "spideryarn"."revision_step_runs" n
                      WHERE n."revision_id" = o."revision_id" AND n."step_name" = 'bibliography');
  SELECT count(*) INTO unequal
    FROM "spideryarn"."article_revisions"
   WHERE "citations" IS DISTINCT FROM "bibliography";
  IF missing > 0 OR unequal > 0 THEN
    RAISE EXCEPTION
      'migration bibliography_expand: % citations step run(s) without a bibliography twin and % revision(s) whose two columns differ', missing, unequal;
  END IF;
END $$;
