-- Every feedback report gets a number, and the ones already filed get theirs in
-- the order they were filed.
--
-- docs/plans/261007d-earlier-tab-says-what-became-of-each-report-numbers-them-and-asks-greg-questions-in-place.md,
-- decision 5. Greg, 2026-10-06 (spya-cnbv8f): "give every single feedback
-- report its own ID somehow, so that it would be easy for us to refer to them
-- in conversation." A report's `spya-` id is minted by a browser and is unique
-- only per owner; `number` is one sequence across all owners.
--
-- ## Why this file is hand-edited
--
-- Drizzle generated one statement: add the column as `NOT NULL GENERATED BY
-- DEFAULT AS IDENTITY`. Postgres would then number the existing rows itself, in
-- whatever order it happened to read them off the heap. The number is something
-- people say out loud, so the old reports are numbered by when they were filed:
-- the column arrives plain, is filled by `row_number()` over
-- `(created_at, owner_id, id)` (a total order, the primary key breaks any tie),
-- and only then becomes the identity column drizzle's snapshot records. The end
-- state is exactly what the generated statement would have left.
--
-- ## The sequence is moved past the backfill
--
-- `setval` puts the sequence on the highest number given out, so the next
-- insert gets the one after it. Without it the next report would be handed 1
-- and fail the unique index (GPT Sol's plan review, F6). On an empty table
-- `max` is null, `setval` is strict and does nothing, and the first report is 1.
--
-- Drizzle applies every pending migration in one transaction, so no report can
-- be filed between these statements. Code deployed before this column names no
-- `number` in its insert and is handed the next one by the identity default;
-- an identity column needs no grant on its sequence. tests/feedback-store.test.ts
-- runs this file's own text against a copy of the table.
ALTER TABLE "spideryarn"."feedback" ADD COLUMN "number" integer;--> statement-breakpoint
UPDATE "spideryarn"."feedback" AS f
   SET "number" = filed.n
  FROM (
    SELECT owner_id, id, row_number() OVER (ORDER BY created_at, owner_id, id) AS n
      FROM "spideryarn"."feedback"
  ) AS filed
 WHERE f.owner_id = filed.owner_id AND f.id = filed.id;--> statement-breakpoint
ALTER TABLE "spideryarn"."feedback" ALTER COLUMN "number" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "spideryarn"."feedback" ALTER COLUMN "number" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "spideryarn"."feedback_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"spideryarn"."feedback_number_seq"', (SELECT max("number") FROM "spideryarn"."feedback"));--> statement-breakpoint
CREATE UNIQUE INDEX "feedback_number_unique" ON "spideryarn"."feedback" USING btree ("number");
