-- Tutorial, Remember's third sub-mode: a fourth chat_threads.kind, and one per
-- article like Remember. docs/plans/261002i-one-adaptive-recall-and-a-tutorial-sub-mode-for-remember.md.
--
-- Generated by drizzle-kit. A WIDENING of the CHECK, the safe direction (as
-- 0050_candidates_thread_kind.sql was): every existing row satisfies the wider
-- one. The unique index needs no fold, because no row has kind 'tutorial' until
-- this migration allows one.
--
-- One hand edit: IF NOT EXISTS on the index. This file was first generated as
-- 20261002214711_tutorial_thread_kind, which forked with dev's
-- 20261002215335_feedback_notice_bucket (both index 122) and was regenerated
-- after it. The local database the worktrees share had already applied the
-- first one, so the index can be there already; the CHECK half is a drop and a
-- re-add and needs nothing.
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_kind";--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "chat_threads_one_tutorial" ON "spideryarn"."chat_threads" USING btree ("article_id") WHERE "spideryarn"."chat_threads"."kind" = 'tutorial';--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_kind" CHECK ("spideryarn"."chat_threads"."kind" in ('chat','remember','candidates','tutorial'));