-- The `hierarchy` step becomes `structure`: the step name in the CHECK and the
-- rows, and the step's three checkpoint namespaces.
-- docs/plans/261002b-rename-the-hierarchy-step-to-structure-everywhere.md § Stage 2.
--
-- Generated by drizzle-kit (the two CHECK pairs), then the guards and the data
-- movement inserted BETWEEN the DROPs and the re-ADDs. That order is the point:
-- Postgres validates a re-added CHECK against the rows already in the table, so
-- narrowing before the rows move fails with a 23514 — and passes on an empty
-- local container, failing only where there is history. `0041` (`toc` →
-- `hierarchy`) and `20261001224759_skim` are the precedents.
--
-- **Both CHECKs are hand-kept in src/db/schema.ts.** tests/db-step-constraint.test.ts
-- compares the last `revision_step_runs_step` here with `STEP_ORDER`, and
-- tests/db-schema.test.ts the namespace list with `CHECKPOINT_NAMESPACES`.
--
-- What is deliberately NOT rewritten (plan § What changes name, and what does not):
--
-- - `ai_calls.purpose` / `ai_calls.step_name` / `ai_calls.job` — the ledger is
--   append-only. `RENAMED` in src/cost-categories.ts classifies an old
--   `hierarchy` row as `structure`.
-- - `jobs.work_key` — a sha256 over the ordered step names that SQL cannot
--   recompute. For a finished job it is history; the drain guard below is why no
--   live job can hold one spelled the old way.
-- - `revision_step_runs.prompt_version` and the tree's `version` (`toc/11`,
--   `expand/7`): they name the prompt, which is unchanged.
-- - `jobs.steps[].label` ("Building the hierarchy"): words shown for a job that
--   has finished, not a name anything matches on.
-- - `feedback` rows: evidence, kept as sent.
--
-- **Checkpoint keys do not move**: `checkpointKey` (src/source-hash.ts) hashes
-- only the caller's object, never the namespace, so a moved row is found again
-- by the same key and an article mid-labelling resumes rather than re-buying
-- its calls.

-- **The drain guard** (GPT Sol, plan review F1). `hierarchy` is in every
-- ordinary ingest. A worker running old code mid-step would finish against a
-- row this renames (`StepRunNotHeld`, src/store/pg-revisions.ts), or write its
-- in-memory `JobStep[]` back with the old name after the postcondition below
-- has run; and a live job's `work_key` hashes the old name, so a re-submitted
-- URL would not match it. So: drained-or-nothing. The RAISE aborts the whole
-- transaction, the database is left exactly as it was, and the migration can
-- simply be run again once the queue is clear.
--
-- A job naming BOTH spellings is anomalous (`orderSteps` in src/jobs.ts keeps
-- each step at most once) and refused too, rather than collapsed into two
-- `structure` entries whose statuses cannot be reconciled.
DO $$
DECLARE live bigint;
DECLARE mixed_steps bigint;
DECLARE mixed_reset bigint;
BEGIN
  SELECT count(*) INTO live FROM "spideryarn"."jobs"
   WHERE "status" IN ('queued', 'running')
     AND ("steps" @> '[{"name":"hierarchy"}]'::jsonb
          OR "reset"->'regenerate' @> '["hierarchy"]'::jsonb);
  IF live > 0 THEN
    RAISE EXCEPTION
      'migration structure_step refused: % queued/running job(s) still name a "hierarchy" step. A worker on the old code may still be inside one, and its work_key hashes the old name. Let the queue drain (or cancel those jobs) and run this again.', live;
  END IF;
  SELECT count(*) INTO mixed_steps FROM "spideryarn"."jobs"
   WHERE "steps" @> '[{"name":"hierarchy"}]'::jsonb
     AND "steps" @> '[{"name":"structure"}]'::jsonb;
  SELECT count(*) INTO mixed_reset FROM "spideryarn"."jobs"
   WHERE "reset"->'regenerate' @> '["hierarchy"]'::jsonb
     AND "reset"->'regenerate' @> '["structure"]'::jsonb;
  IF mixed_steps > 0 OR mixed_reset > 0 THEN
    RAISE EXCEPTION
      'migration structure_step: cannot safely merge both spellings in % jobs.steps row(s) and % jobs.reset row(s); inspect those jobs before retrying.', mixed_steps, mixed_reset;
  END IF;
END $$;--> statement-breakpoint
ALTER TABLE "spideryarn"."checkpoints" DROP CONSTRAINT "checkpoints_namespace";--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" DROP CONSTRAINT "revision_step_runs_step";--> statement-breakpoint
UPDATE "spideryarn"."revision_step_runs" SET "step_name" = 'structure' WHERE "step_name" = 'hierarchy';--> statement-breakpoint
-- Spelled out, no pattern: the first pass is renamed as well as the step
-- (`hierarchy-structure` → `structure-whole-document`, plan § The name collision).
UPDATE "spideryarn"."checkpoints" SET "namespace" = CASE "namespace"
    WHEN 'hierarchy-structure' THEN 'structure-whole-document'
    WHEN 'hierarchy-deepen' THEN 'structure-deepen'
    WHEN 'hierarchy-labels' THEN 'structure-labels'
  END
 WHERE "namespace" IN ('hierarchy-structure', 'hierarchy-deepen', 'hierarchy-labels');--> statement-breakpoint
-- `jobs.steps` is a `JobStep[]` — its elements are OBJECTS, `{"name":"hierarchy",…}`,
-- not bare strings, so `steps @> '["hierarchy"]'` would match nothing and still
-- report success. `e->>'name'` reads the field; `WITH ORDINALITY` and `ORDER BY`
-- give the original order back, and for `steps` the order is the meaning.
-- docs/project/sql.md § Migrating data inside a JSONB column.
UPDATE "spideryarn"."jobs" SET "steps" = (
  SELECT jsonb_agg(CASE WHEN e->>'name' = 'hierarchy'
                        THEN jsonb_set(e, '{name}', '"structure"')
                        ELSE e END ORDER BY ord)
    FROM jsonb_array_elements("steps") WITH ORDINALITY AS t(e, ord)
) WHERE "steps" @> '[{"name":"hierarchy"}]'::jsonb;--> statement-breakpoint
-- `jobs.reset` is a `JobReset`, `{ regenerate: StepName[]; profile?: string }`
-- (src/types.ts): here the elements ARE bare strings. Order kept the same way.
UPDATE "spideryarn"."jobs" SET "reset" = jsonb_set("reset", '{regenerate}', (
  SELECT jsonb_agg(CASE WHEN e #>> '{}' = 'hierarchy' THEN '"structure"'::jsonb ELSE e END ORDER BY ord)
    FROM jsonb_array_elements("reset"->'regenerate') WITH ORDINALITY AS t(e, ord)
)) WHERE "reset"->'regenerate' @> '["hierarchy"]'::jsonb;--> statement-breakpoint
-- **The postcondition**, because the `jobs` rewrites have no constraint to catch
-- them: "matched nothing" and "worked" print the same tick. The re-added CHECKs
-- below are the proof for `revision_step_runs` and `checkpoints`.
DO $$
DECLARE left_behind bigint;
BEGIN
  SELECT (SELECT count(*) FROM "spideryarn"."jobs" WHERE "steps" @> '[{"name":"hierarchy"}]'::jsonb)
       + (SELECT count(*) FROM "spideryarn"."jobs" WHERE "reset"->'regenerate' @> '["hierarchy"]'::jsonb)
    INTO left_behind;
  IF left_behind > 0 THEN
    RAISE EXCEPTION
      'migration structure_step: % job row(s) still name a "hierarchy" step in jobs.steps or jobs.reset after the rewrites — the statements above matched less than they should have.', left_behind;
  END IF;
END $$;--> statement-breakpoint
ALTER TABLE "spideryarn"."checkpoints" ADD CONSTRAINT "checkpoints_namespace" CHECK ("spideryarn"."checkpoints"."namespace" in ('structure-deepen','structure-labels','structure-whole-document','pdf-chunk'));--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" ADD CONSTRAINT "revision_step_runs_step" CHECK ("spideryarn"."revision_step_runs"."step_name" in ('fetch','metadata','extract','blocks','structure','labels','assets','arc','tweets','glossary','quotes','skim','ideas','timeline','quiz','faq','sketch','illustrated','debate','citations','crossrefs','simple'));
