-- The thread kind `remember` becomes `learn`: in the constraint, in the rows,
-- and in the one-per-article index that names it.
-- docs/plans/261006a-remember-identifiers-become-learn-all-the-way-down.md
--
-- Generated by drizzle-kit (the four DDL statements, in this order), then the
-- data movement was inserted by hand: the UPDATE, after the two DROPs and
-- before the CREATE and the ADD. That order is the whole point, and it is the
-- trap 0048_rename_review_thread_kind.sql wrote down when `review` became
-- `remember`: Postgres validates a re-added CHECK against the rows already in
-- the table, so narrowing before the data moves fails with a 23514 — and it
-- fails only where there is history, passing cleanly on an empty container.
-- `drizzle-kit generate` diffs src/db/schema.ts and cannot see a data movement
-- at all, so it will never emit the UPDATE; a reader regenerating this file
-- will get the four statements without it, and that file would be wrong.
--
-- **The index is dropped and created, never renamed.** A partial index's
-- predicate cannot be altered, so `ALTER INDEX … RENAME` would leave an index
-- called `chat_threads_one_learn` still guarding `kind = 'remember'`, a value
-- no row has after this: a guard by name and none in fact. It is created after
-- the rows are rewritten, so it is built over the rows it will guard. The old
-- index held at most one `remember` thread per article and the UPDATE changes
-- no `article_id`, so the new one cannot meet a duplicate.
--
-- **The re-added CHECK is the postcondition**, as in 0048: a single surviving
-- `remember` row makes it fail with 23514, and the whole migration is one
-- transaction, so a refusal leaves the database exactly as it was. Nothing but
-- `kind` is written: a thread keeps its id, title, timestamps and messages,
-- and the two advisory pointers at a thread (`realtime_sessions.thread_id`,
-- `comments.thread_id`) go on resolving by identity.
--
-- **`chat_threads.title` is left alone.** A Recall thread's stored title is
-- the placeholder `Remembering`; that is a word a reader may see, not an
-- identifier, and it is not this migration's to change.
--
-- No wire alias: src/routes.ts refuses `kind: "remember"` with a 400, as it
-- refused `review` after 0048, so a tab left open across the deploy fails its
-- next Recall turn until it reloads.
--
-- **Code that does not know `learn` yet** — the deploy before this one, or
-- another worktree on the shared local database — is covered by stage 0 of the
-- plan: `storedThreadKind` (src/types.ts) throws on a stored kind it does not
-- know, where it used to coerce it to `chat`. So old code reading a migrated
-- row fails that article's chat reads rather than answering a Recall thread
-- with Chat's prompt and storing the answer. Old code *inserting* a
-- `remember` thread fails this CHECK: a failed turn, retried after a reload.
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_kind";--> statement-breakpoint
DROP INDEX "spideryarn"."chat_threads_one_remember";--> statement-breakpoint
UPDATE "spideryarn"."chat_threads" SET "kind" = 'learn' WHERE "kind" = 'remember';--> statement-breakpoint
CREATE UNIQUE INDEX "chat_threads_one_learn" ON "spideryarn"."chat_threads" USING btree ("article_id") WHERE "spideryarn"."chat_threads"."kind" = 'learn';--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_kind" CHECK ("spideryarn"."chat_threads"."kind" in ('chat','learn','candidates','tutorial','explore'));
