-- One Remember thread per article: fold any duplicates into the earliest, then
-- create the unique index that keeps it so.
-- docs/plans/261001m-remember-is-its-own-single-thread.md § Design 1–2, and
-- § Changed by GPT Sol's plan review (F2, F5, F7, F8, F9).
--
-- Generated by drizzle-kit (the CREATE UNIQUE INDEX at the bottom), then the
-- fold was inserted ABOVE it by hand. The order is the whole point, the same
-- trap 0048_rename_review_thread_kind.sql wrote down: creating a unique index
-- validates it against the rows already in the table, so on any database with
-- two Remember threads on one article the index alone fails — and it passes
-- cleanly on an empty container. `drizzle-kit generate` diffs src/db/schema.ts
-- and cannot see a data movement, so a reader regenerating this file gets the
-- index without the fold, and that file would be wrong.
--
-- Production had no article with more than one Remember thread when this was
-- written (2026-10-01, read-only), so there the fold moves nothing and the
-- index is the part that does the work. The fold is for every other database,
-- and for the window between that measurement and the deploy.
--
-- **Fails loudly rather than losing anything.** The migrator runs every pending
-- file in one transaction, so any RAISE or constraint violation below leaves
-- the database exactly as it was:
--   - a pending answer with a live attempt in a thread being folded RAISEs
--     (its writer matches on the old thread id and would be orphaned);
--   - a moved message whose id is already in the kept thread violates
--     `chat_messages`' primary key — there is deliberately no
--     `on conflict do nothing`, which would drop a turn in silence.

-- F5: no instance still running the old code may insert a second Remember
-- thread between the fold and the index. SHARE ROW EXCLUSIVE blocks every
-- writer of chat_threads and is held to the end of the transaction, through
-- the index build; readers carry on.
LOCK TABLE "spideryarn"."chat_threads" IN SHARE ROW EXCLUSIVE MODE;--> statement-breakpoint

-- F7: the mapping every later statement is driven by — one row per thread
-- being folded away, naming its article and the thread it folds into. The
-- keeper is the earliest created, ties broken by id. Keyed on article_id alone
-- (F9): an article has exactly one owner, so this is one per reader too.
CREATE TEMP TABLE "remember_fold" ON COMMIT DROP AS
SELECT "article_id", "folded_id", "folded_created_at", "kept_id"
FROM (
  SELECT
    "article_id",
    "id" AS "folded_id",
    "created_at" AS "folded_created_at",
    first_value("id") OVER (
      PARTITION BY "article_id" ORDER BY "created_at", "id"
    ) AS "kept_id"
  FROM "spideryarn"."chat_threads"
  WHERE "kind" = 'remember'
) "ranked"
WHERE "folded_id" <> "kept_id";--> statement-breakpoint

-- F2: refuse to fold a thread with an answer still being written. Production
-- had none; if this fires, wait for the answer (or the sweep) and migrate again.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "spideryarn"."chat_messages" "m"
    JOIN "remember_fold" "f"
      ON "m"."article_id" = "f"."article_id" AND "m"."thread_id" = "f"."folded_id"
    WHERE "m"."status" = 'pending' AND "m"."attempt_id" IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'chat_threads_one_remember: a Remember thread to be folded has an answer still in flight; nothing was changed';
  END IF;
END
$$;--> statement-breakpoint

-- Move every message of the folded threads into the keeper. Conversation by
-- conversation, in the order the threads were created, each keeping its own
-- internal order — never interleaved by timestamp, which could separate a
-- question from its answer. F8: numbering starts at the keeper's
-- max(ordinal) + 1, not its count, so a keeper with a gap cannot collide.
-- Only thread_id and ordinal change; every other column stays as it was.
UPDATE "spideryarn"."chat_messages" "m"
SET "thread_id" = "mv"."kept_id", "ordinal" = "mv"."new_ordinal"
FROM (
  SELECT
    "msg"."article_id",
    "msg"."thread_id",
    "msg"."id",
    "f"."kept_id",
    coalesce((
      SELECT max("k"."ordinal")
      FROM "spideryarn"."chat_messages" "k"
      WHERE "k"."article_id" = "f"."article_id" AND "k"."thread_id" = "f"."kept_id"
    ), -1)
    + row_number() OVER (
      PARTITION BY "f"."article_id"
      ORDER BY "f"."folded_created_at", "f"."folded_id", "msg"."ordinal"
    ) AS "new_ordinal"
  FROM "spideryarn"."chat_messages" "msg"
  JOIN "remember_fold" "f"
    ON "msg"."article_id" = "f"."article_id" AND "msg"."thread_id" = "f"."folded_id"
) "mv"
WHERE "m"."article_id" = "mv"."article_id"
  AND "m"."thread_id" = "mv"."thread_id"
  AND "m"."id" = "mv"."id";--> statement-breakpoint

-- The keeper's clock becomes the group's latest, so the conversation sorts by
-- its most recent turn. Its id, title, kind and created_at are untouched.
UPDATE "spideryarn"."chat_threads" "t"
SET "updated_at" = "g"."latest"
FROM (
  SELECT "f"."article_id", "f"."kept_id", max("ft"."updated_at") AS "latest"
  FROM "remember_fold" "f"
  JOIN "spideryarn"."chat_threads" "ft"
    ON "ft"."article_id" = "f"."article_id" AND "ft"."id" = "f"."folded_id"
  GROUP BY "f"."article_id", "f"."kept_id"
) "g"
WHERE "t"."article_id" = "g"."article_id"
  AND "t"."id" = "g"."kept_id"
  AND "g"."latest" > "t"."updated_at";--> statement-breakpoint

-- The two advisory pointers at a thread (text, no foreign key), repointed by
-- article AND id: thread ids are only unique within an article.
UPDATE "spideryarn"."realtime_sessions" "r"
SET "thread_id" = "f"."kept_id"
FROM "remember_fold" "f"
WHERE "r"."article_id" = "f"."article_id" AND "r"."thread_id" = "f"."folded_id";--> statement-breakpoint

UPDATE "spideryarn"."comments" "c"
SET "thread_id" = "f"."kept_id"
FROM "remember_fold" "f"
WHERE "c"."article_id" = "f"."article_id" AND "c"."thread_id" = "f"."folded_id";--> statement-breakpoint

-- The folded threads are empty by now. `chat_messages_thread_fk` cascades, so
-- a message the move missed would go with its thread — the test asserts the
-- count before and after for exactly that reason.
DELETE FROM "spideryarn"."chat_threads" "t"
USING "remember_fold" "f"
WHERE "t"."article_id" = "f"."article_id" AND "t"."id" = "f"."folded_id";--> statement-breakpoint

CREATE UNIQUE INDEX "chat_threads_one_remember" ON "spideryarn"."chat_threads" USING btree ("article_id") WHERE "spideryarn"."chat_threads"."kind" = 'remember';
