-- Explore, Remember's fourth sub-mode: a fifth chat_threads.kind, and one per
-- article like Remember and Tutorial. docs/plans/261003l-reader-notes-chat-tool-and-explore-sub-mode-of-remember.md.
--
-- Generated by drizzle-kit, with no hand edit below this comment. Additive: a
-- WIDENING of the CHECK, the safe direction (as 0050_candidates_thread_kind.sql
-- and 20261002232057_tutorial_thread_kind.sql were) -- every existing row
-- satisfies the wider one, so it is a drop and a re-add with no data movement.
-- The unique index needs no fold, because no row has kind 'explore' until this
-- migration allows one.
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_kind";--> statement-breakpoint
CREATE UNIQUE INDEX "chat_threads_one_explore" ON "spideryarn"."chat_threads" USING btree ("article_id") WHERE "spideryarn"."chat_threads"."kind" = 'explore';--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_kind" CHECK ("spideryarn"."chat_threads"."kind" in ('chat','remember','candidates','tutorial','explore'));