-- Tutorial, Remember's third sub-mode: a fourth chat_threads.kind, and one per
-- article like Remember. docs/plans/261002i-one-adaptive-recall-and-a-tutorial-sub-mode-for-remember.md.
--
-- Generated by drizzle-kit and left as generated. A WIDENING of the CHECK, the
-- safe direction (as 0050_candidates_thread_kind.sql was): every existing row
-- satisfies the wider one. The unique index needs no fold, because no row has
-- kind 'tutorial' until this migration allows one.
ALTER TABLE "spideryarn"."chat_threads" DROP CONSTRAINT "chat_threads_kind";--> statement-breakpoint
CREATE UNIQUE INDEX "chat_threads_one_tutorial" ON "spideryarn"."chat_threads" USING btree ("article_id") WHERE "spideryarn"."chat_threads"."kind" = 'tutorial';--> statement-breakpoint
ALTER TABLE "spideryarn"."chat_threads" ADD CONSTRAINT "chat_threads_kind" CHECK ("spideryarn"."chat_threads"."kind" in ('chat','remember','candidates','tutorial'));