-- Trajectory becomes Skim: the column, the step name in the CHECK, and the rows.
-- docs/plans/261001r-trajectory-becomes-skim-and-marginalia-rename-audit.md § Stage 2.
--
-- Generated by drizzle-kit (the RENAME and the CHECK pair, answered "rename
-- column" rather than "create column" at its prompt), then the data movement
-- inserted BETWEEN the DROP and the re-ADD of the CHECK. That order is the point:
-- Postgres validates a re-added CHECK against the rows already in the table, so
-- narrowing before the rows move fails with a 23514 — and passes on an empty
-- local container, failing only where there is history. drizzle/0041 is the
-- precedent (`toc` → `hierarchy`).
--
-- **The CHECK is hand-kept in src/db/schema.ts.** `tests/db-step-constraint.test.ts`
-- compares the last `ADD CONSTRAINT` here with `STEP_ORDER` in both directions.
--
-- What is deliberately NOT rewritten (plan § After the plan review):
--
-- - `ai_calls.purpose` / `ai_calls.step_name` — the ledger is append-only.
--   src/cost-categories.ts § `RENAMED` classifies an old `trajectory` row with
--   `skim` instead (F6).
-- - `jobs.work_key` — a sha256 over the ordered step names that SQL cannot
--   recompute (src/jobs.ts § `workKeyFor`). For a finished job it is history; a
--   job queued or running across the deploy keeps a key spelled the old way, and
--   the worst it costs is one duplicate run (F5). Unlike 0041 this does not
--   refuse while such a job exists — accepted as a stated window.
-- - the stored route's `version` (`trajectory/7`) and
--   `revision_step_runs.prompt_version`: the prompt is unchanged and the tag
--   still names it (src/skim.ts § `PROMPT_VERSION`, F1).
-- - `feedback` rows: evidence, kept as sent (F4).
-- A valid job has each step at most once (`orderSteps` in src/jobs.ts). A row
-- carrying BOTH names is therefore anomalous. Blind replacement would make two
-- `skim` entries and leave their distinct statuses/force flags irreconcilable;
-- choosing either one would silently throw real progress away. Refuse before
-- changing anything, including the equivalent ambiguity in a reset plan.
DO $$
DECLARE mixed_steps bigint;
DECLARE mixed_reset bigint;
BEGIN
  SELECT count(*) INTO mixed_steps FROM "spideryarn"."jobs"
   WHERE "steps" @> '[{"name":"trajectory"}]'::jsonb
     AND "steps" @> '[{"name":"skim"}]'::jsonb;
  SELECT count(*) INTO mixed_reset FROM "spideryarn"."jobs"
   WHERE "reset"->'regenerate' @> '["trajectory"]'::jsonb
     AND "reset"->'regenerate' @> '["skim"]'::jsonb;
  IF mixed_steps > 0 OR mixed_reset > 0 THEN
    RAISE EXCEPTION
      'migration skim: cannot safely merge both spellings in % jobs.steps row(s) and % jobs.reset row(s); inspect those jobs before retrying.', mixed_steps, mixed_reset;
  END IF;
END $$;--> statement-breakpoint
ALTER TABLE "spideryarn"."article_revisions" RENAME COLUMN "trajectory" TO "skim";--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" DROP CONSTRAINT "revision_step_runs_step";--> statement-breakpoint
UPDATE "spideryarn"."revision_step_runs" SET "step_name" = 'skim' WHERE "step_name" = 'trajectory';--> statement-breakpoint
-- `jobs.steps` is a `JobStep[]` — its elements are OBJECTS, `{"name":"trajectory",…}`,
-- not bare strings, so `steps @> '["trajectory"]'` would match nothing and still
-- report success. `e->>'name'` reads the field; `WITH ORDINALITY` and `ORDER BY`
-- give the original order back, and for `steps` the order is the meaning.
-- docs/project/sql.md § Migrating data inside a JSONB column.
UPDATE "spideryarn"."jobs" SET "steps" = (
  SELECT jsonb_agg(CASE WHEN e->>'name' = 'trajectory'
                        THEN jsonb_set(e, '{name}', '"skim"')
                        ELSE e END ORDER BY ord)
    FROM jsonb_array_elements("steps") WITH ORDINALITY AS t(e, ord)
) WHERE "steps" @> '[{"name":"trajectory"}]'::jsonb;--> statement-breakpoint
-- `jobs.reset` is a `JobReset`, `{ regenerate: StepName[]; profile?: string }`
-- (src/types.ts): here the elements ARE bare strings. Order kept the same way.
UPDATE "spideryarn"."jobs" SET "reset" = jsonb_set("reset", '{regenerate}', (
  SELECT jsonb_agg(CASE WHEN e #>> '{}' = 'trajectory' THEN '"skim"'::jsonb ELSE e END ORDER BY ord)
    FROM jsonb_array_elements("reset"->'regenerate') WITH ORDINALITY AS t(e, ord)
)) WHERE "reset"->'regenerate' @> '["trajectory"]'::jsonb;--> statement-breakpoint
-- **The postcondition**, because the two `jobs` rewrites have no constraint to
-- catch them: "matched nothing" and "worked" print the same tick. The re-added
-- CHECK below is the proof for `revision_step_runs`.
DO $$
DECLARE left_behind bigint;
BEGIN
  SELECT (SELECT count(*) FROM "spideryarn"."jobs" WHERE "steps" @> '[{"name":"trajectory"}]'::jsonb)
       + (SELECT count(*) FROM "spideryarn"."jobs" WHERE "reset"->'regenerate' @> '["trajectory"]'::jsonb)
    INTO left_behind;
  IF left_behind > 0 THEN
    RAISE EXCEPTION
      'migration skim: % job row(s) still name a "trajectory" step in jobs.steps or jobs.reset after the rewrites — the statements above matched less than they should have.', left_behind;
  END IF;
END $$;--> statement-breakpoint
ALTER TABLE "spideryarn"."revision_step_runs" ADD CONSTRAINT "revision_step_runs_step" CHECK ("spideryarn"."revision_step_runs"."step_name" in ('fetch','extract','blocks','hierarchy','labels','assets','arc','tweets','glossary','quotes','skim','ideas','timeline','quiz','faq','sketch','illustrated','debate','citations','crossrefs','simple'));
