/**
 * The attention list, in and out of `~/.overseer/current.json`.
 *
 * A separate file from tests/overseer-store.test.ts on purpose: that file and
 * the store's core are another session's stage, and this is a field added beside
 * them. It is the same store and the same round trip.
 *
 * **The decision under test is a DEGRADATION, and it is the opposite of the one
 * the register gets.** The register is the thing there is no second copy of, so a
 * bad entry fails the whole checkpoint and the event log is replayed. The
 * attention list is regenerated by the next pass for a few model calls, so a
 * malformed one must not force that replay — but it must also never come back as
 * an empty list, because absent, malformed and *nothing needs you* are three
 * different facts and only the third is a claim.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, test } from "vitest";

import { inboxLines } from "../scripts/overseer.js";
import { runOverseer } from "../tools/overseer/daemon.js";

import type { AttentionList } from "../tools/fleet/wire.js";
import { MAX_ASKS_CHARS, MIN_ASKS_CHARS } from "../tools/overseer/attention-classify.js";
import {
  CHECKPOINT_FILE,
  attentionNotYetRun,
  describeRefusal,
  openStore,
  readCheckpoint,
  type OverseerStore,
} from "../tools/overseer/store.js";

const opened: OverseerStore[] = [];
const roots: string[] = [];

afterEach(() => {
  for (const store of opened.splice(0)) store.close();
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function tempRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "overseer-attention-store-"));
  roots.push(root);
  return root;
}

/**
 * A quote of exactly `n` characters, words joined by single spaces — already in
 * the producer's normalised form, with several words at every length used here,
 * so the character bound is what a case tests.
 */
function quoteOf(n: number): string {
  const s = "shall I ship it to dev now ".repeat(Math.ceil(n / 27) + 1).slice(0, n);
  return s.endsWith(" ") ? `${s.slice(0, -1)}x` : s;
}

function mustOpen(root: string, now?: () => Date): OverseerStore {
  const result = openStore({ root, ...(now === undefined ? {} : { now }) });
  if (!result.ok) throw new Error(`expected to open the store, got: ${describeRefusal(result.refusal)}`);
  opened.push(result.store);
  return result.store;
}

const LIST: AttentionList = {
  kind: "list",
  items: [
    {
      id: "abc123",
      sessionId: "$215",
      sessionName: "gjd-remote-on-remote-box",
      waitingSince: "2026-09-08T02:11:00.000Z",
      kind: "irreversible",
      evidence: { kind: "prose", excerpt: "Say the word and I'll shut it down.", why: "it named an action and stopped" },
      answerability: { kind: "phone" },
      duplicates: [],
      proposal: {
        kind: "proposed",
        id: "fp-1:v2",
        recipient: "fable",
        reason: "it is a question of wording",
        asks: "Say the word and I'll shut it down.",
        by: { kind: "model", model: "openai/gpt-5.6-luna", via: "overseer" },
        reach: { kind: "unavailable", why: "the last usage pass found the account limited" },
      },
    },
  ],
  sessionsScanned: 32,
  sessionsUnreadable: 0,
  scannedAt: "2026-09-08T12:40:00.000Z",
};

/** The same pass, with the model refused by the day budget part-way through. */
const LIMITED: AttentionList = {
  kind: "limited",
  items: LIST.kind === "list" ? LIST.items : [],
  sessionsScanned: 32,
  sessionsUnreadable: 4,
  scannedAt: "2026-09-08T12:40:00.000Z",
  stopped: { kind: "exhausted", why: "the day's ceiling of $1.50 would be crossed", until: "2026-09-09T00:00:00.000Z" },
};

describe("the attention list on the checkpoint", () => {
  test("it goes out and comes back whole", () => {
    const root = tempRoot();
    const store = mustOpen(root);
    const written = store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    expect(written.ok).toBe(true);
    if (!written.ok) throw new Error("unreachable");
    expect(written.checkpoint.attention).toEqual(LIST);
    const read = readCheckpoint(root);
    expect(read.kind).toBe("checkpoint");
    if (read.kind !== "checkpoint") return;
    expect(read.checkpoint.attention).toEqual(LIST);
  });

  test("a `limited` list — the model was refused — goes out and comes back whole", () => {
    // Plan 260910f D6: a stopped model pass is its own arm, so this parser has to
    // know it, every field, strictly, the way it knows `list`.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIMITED });
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("unreachable");
    expect(read.checkpoint.attention).toEqual(LIMITED);
    // …and the status line says the judge was stopped rather than that the
    // fleet is calm.
    expect(inboxLines(read.checkpoint.attention, Date.parse("2026-09-08T12:41:00.000Z")).join("\n")).toContain(
      "NOT EVERY SESSION IS BEING JUDGED",
    );
  });

  test("a `limited` list with a malformed `stopped` degrades to `unknown`, never to a list", () => {
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    for (const stopped of [undefined, { kind: "exhausted", why: "spent" }, { kind: "tired", why: "x", until: LIST.scannedAt }, { kind: "exhausted", why: "", until: LIST.scannedAt }]) {
      const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
      raw["attention"] = { ...LIMITED, stopped };
      writeFileSync(path, JSON.stringify(raw, null, 2));
      const read = readCheckpoint(root);
      if (read.kind !== "checkpoint") throw new Error("unreachable");
      expect(read.checkpoint.attention.kind, JSON.stringify(stopped)).toBe("unknown");
    }
  });

  test("an arm this reader does not know is rejected into `unknown` — which is how an OLDER reader meets `limited`", () => {
    // The compatibility half of D6. We cannot run the old build, so this pins
    // the behaviour it had and still has: an unknown kind is a loud `unknown`,
    // never read as the `list` fields it happens to carry. That is the whole
    // reason `limited` is a new kind rather than a field on `list` — a field
    // would have been dropped and the empty list drawn as calm.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    raw["attention"] = { ...LIMITED, kind: "limited-v2", items: [] };
    writeFileSync(path, JSON.stringify(raw, null, 2));
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("unreachable");
    expect(read.checkpoint.attention.kind).toBe("unknown");
  });

  test("a write that carries no new list keeps the one already published", () => {
    // The pass costs money and runs less often than a tick, so most writes carry
    // nothing. Blanking the inbox on those would make it flash empty every 30
    // seconds — and an empty inbox is a claim.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const later = store.checkpoint({ lastGoodSnapshotAt: null, tick: true });
    if (!later.ok) throw new Error("unreachable");
    expect(later.checkpoint.attention).toEqual(LIST);
    // …and it still says when it was scanned, so a held list cannot pass itself
    // off as fresh.
    expect(later.checkpoint.writtenAt).not.toBe(later.checkpoint.attention.scannedAt);
  });

  test("before any pass has run it says nothing has looked, not that nothing needs you", () => {
    const root = tempRoot();
    const store = mustOpen(root);
    const written = store.checkpoint({ lastGoodSnapshotAt: null, tick: true });
    if (!written.ok) throw new Error("unreachable");
    expect(written.checkpoint.attention.kind).toBe("unknown");
    if (written.checkpoint.attention.kind !== "unknown") return;
    expect(written.checkpoint.attention.why).toContain("nothing has been looked at");
  });

  test("a checkpoint written before this field existed reads as `unknown`, not as empty", () => {
    // NO SCHEMA BUMP: a reader that ignores the field draws no inbox, which is
    // poorer rather than wrong. But the reverse — a checkpoint with no field —
    // must not be read as a calm fleet, which would be the most reassuring
    // possible lie about a store that predates the probe.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    delete raw["attention"];
    writeFileSync(path, JSON.stringify(raw, null, 2));

    const read = readCheckpoint(root);
    expect(read.kind).toBe("checkpoint");
    if (read.kind !== "checkpoint") return;
    expect(read.checkpoint.attention.kind).toBe("unknown");
    if (read.checkpoint.attention.kind !== "unknown") return;
    expect(read.checkpoint.attention.why).toContain("before the Overseer had one");
  });

  test("a malformed list degrades to `unknown` and does NOT fail the whole checkpoint", () => {
    // The opposite decision from the register, and the difference is whether
    // there is a second copy. Failing whole here would pay a full log replay for
    // something the next pass regenerates for a few model calls.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    raw["attention"] = { kind: "list", items: [{ id: "x" }], sessionsScanned: 3, scannedAt: LIST.scannedAt };
    writeFileSync(path, JSON.stringify(raw, null, 2));

    const read = readCheckpoint(root);
    expect(read.kind).toBe("checkpoint");
    if (read.kind !== "checkpoint") return;
    expect(read.checkpoint.attention.kind).toBe("unknown");
  });

  test("an item whose evidence is neither a dialog nor prose is refused", () => {
    // The one place believing a malformed record would matter: a renderer that
    // could not tell the two apart would draw a dialog's affordances on an item
    // we merely INFERRED, which is decision one undone from the disk.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    const list = raw["attention"] as { items: { evidence: unknown }[] };
    list.items[0]!.evidence = { kind: "question", question: "shall I?" };
    writeFileSync(path, JSON.stringify(raw, null, 2));

    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("expected the checkpoint to survive");
    expect(read.checkpoint.attention.kind).toBe("unknown");
  });

  test("a restart does not republish the previous list, because its durations cannot be vouched for", () => {
    // It could be restored from the checkpoint, and it must not be: `waitingSince`
    // is first-seen, and a question answered while we were down would come back
    // wearing a wait we never observed. That is the `13m` bug in `StatusSince`,
    // one level up, and the honest answer is the same — say we do not know.
    const root = tempRoot();
    const first = mustOpen(root);
    first.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    first.close();

    const second = mustOpen(root);
    const written = second.checkpoint({ lastGoodSnapshotAt: null, tick: true });
    if (!written.ok) throw new Error("unreachable");
    expect(written.checkpoint.attention.kind).toBe("unknown");
  });
});

describe("an item's proposal on the checkpoint (plan 260910f Stage 2)", () => {
  const BY = { kind: "model", model: "openai/gpt-5.6-luna", via: "overseer" };
  /** LIST's own quote: in its excerpt, and inside the length bounds. */
  const QUOTE = "Say the word and I'll shut it down.";

  /**
   * The checkpoint with its one item's `proposal` replaced by `proposal`, or
   * removed when `undefined` — and, when given, its `evidence` replaced too.
   */
  function readWithProposal(proposal: unknown, evidence?: unknown): AttentionList {
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    const list = raw["attention"] as { items: Record<string, unknown>[] };
    if (proposal === undefined) delete list.items[0]!["proposal"];
    else list.items[0]!["proposal"] = proposal;
    if (evidence !== undefined) list.items[0]!["evidence"] = evidence;
    writeFileSync(path, JSON.stringify(raw, null, 2));
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("the checkpoint must survive");
    return read.checkpoint.attention;
  }

  const PROPOSED = { kind: "proposed", id: "i", recipient: "sol", reason: "r", asks: QUOTE, by: BY, reach: { kind: "available" } };

  /** A prose excerpt and a quote, together. */
  function readWithQuote(excerpt: string, asks: string): AttentionList {
    return readWithProposal({ ...PROPOSED, asks }, { kind: "prose", excerpt, why: "it named an action and stopped" });
  }

  test("refuses a quote that is not in the same item's excerpt — the card would call it the sentence the proposal is about (F15)", () => {
    expect(readWithQuote("Tell me which one.", "This text is not in the excerpt.").kind).toBe("unknown");
  });

  test("finds the quote under the producer's whitespace normalisation, so a pane's wrapped line still matches (F15)", () => {
    expect(readWithQuote("Say the word and I'll\n   shut it down.", QUOTE).kind).toBe("list");
  });

  test("refuses a proposed quote on a dialog item, which has no excerpt to hold it (F15)", () => {
    expect(readWithProposal(PROPOSED, { kind: "dialog", question: "Say the word?", options: ["Yes", "No"] }).kind).toBe("unknown");
  });

  test.each([
    ["the longest accepted", MAX_ASKS_CHARS, "list"],
    ["one over the longest", MAX_ASKS_CHARS + 1, "unknown"],
    ["the shortest accepted", MIN_ASKS_CHARS, "list"],
    ["one under the shortest", MIN_ASKS_CHARS - 1, "unknown"],
  ])("bounds the quote's length — %s (F17)", (_name, length, kind) => {
    const asks = quoteOf(length);
    expect(asks).toHaveLength(length);
    expect(readWithQuote(`It named an action.\n${asks}`, asks).kind).toBe(kind);
  });

  test("refuses a one-word quote even when it is long enough (F17)", () => {
    expect(readWithQuote("Unbelievably so.", "Unbelievably").kind).toBe("unknown");
  });

  test("an item from an older producer, with no proposal at all, reads as `not-reported` — not a failure", () => {
    const list = readWithProposal(undefined);
    if (list.kind !== "list") throw new Error(`expected a list, got ${list.kind}`);
    expect(list.items[0]?.proposal).toEqual({ kind: "not-reported" });
  });

  test.each([
    ["proposed", LIST.kind === "list" ? LIST.items[0]?.proposal : null],
    ["unplaced", { kind: "unplaced", id: "fp:v2", why: "could be either", by: BY }],
    ["off", { kind: "off", why: "proposals are off" }],
    ["not-reached", { kind: "not-reached", why: "the budget refused the re-read" }],
    ["not-applicable", { kind: "not-applicable" }],
    ["not-reported", { kind: "not-reported" }],
    ["proposed, reach available", { kind: "proposed", id: "i", recipient: "greg", reason: "r", asks: QUOTE, by: BY, reach: { kind: "available" } }],
    ["proposed, reach not checked", { kind: "proposed", id: "i", recipient: "sol", reason: "r", asks: QUOTE, by: BY, reach: { kind: "not-checked", why: "no Codex reading" } }],
  ])("reads the %s arm back whole", (_name, proposal) => {
    const list = readWithProposal(proposal);
    if (list.kind !== "list") throw new Error(`expected a list, got ${list.kind}`);
    expect(list.items[0]?.proposal).toEqual(proposal);
  });

  test.each([
    ["an unknown kind", { kind: "sent", why: "x" }],
    // A quote that is valid in every other way, so each case refuses for its own reason.
    ["an unknown recipient", { kind: "proposed", id: "i", recipient: "gpt", reason: "r", asks: QUOTE, by: BY, reach: { kind: "available" } }],
    ["no reach", { kind: "proposed", id: "i", recipient: "sol", reason: "r", asks: QUOTE, by: BY }],
    ["a blank quote", { kind: "proposed", id: "i", recipient: "sol", reason: "r", asks: "", by: BY, reach: { kind: "available" } }],
    ["an author that is not the model", { kind: "proposed", id: "i", recipient: "sol", reason: "r", asks: QUOTE, by: { kind: "person", model: "Greg", via: "overseer" }, reach: { kind: "available" } }],
    ["an author via somebody else", { kind: "unplaced", id: "i", why: "w", by: { ...BY, via: "greg" } }],
    ["an unplaced answer with no why", { kind: "unplaced", id: "i", by: BY }],
    ["a reach whose why is missing", { kind: "proposed", id: "i", recipient: "fable", reason: "r", asks: QUOTE, by: BY, reach: { kind: "unavailable" } }],
    ["an off with no why", { kind: "off" }],
    ["a proposal that is not an object", "fable"],
  ])("refuses %s — the list degrades to `unknown`, never a proposal half-read", (_name, proposal) => {
    expect(readWithProposal(proposal).kind).toBe("unknown");
  });
});

describe("the checkpoint parser, which must be total — GPT Sol's finding 3", () => {
  // The shape Sol wrote into a real checkpoint. It came back as a valid
  // `kind:"list"` and `inboxLines()` threw on the missing `duplicates`. Every
  // case below is a field the first version accepted by casting.
  const HALF_ITEMS: Record<string, unknown>[] = [
    // Sol's own reproduction, verbatim: enough fields to pass the first version's
    // checks, and not enough for `inboxLines()` to render.
    { id: "x", sessionId: "$1", waitingSince: "2026-09-08T10:00:00.000Z", evidence: { kind: "dialog" } },
    // …and one that is complete except for `duplicates`, which is the field that
    // actually threw.
    {
      id: "y",
      sessionId: "$2",
      sessionName: "a",
      waitingSince: "2026-09-08T10:00:00.000Z",
      kind: "irreversible",
      evidence: { kind: "dialog", question: "q", options: ["a"] },
      answerability: { kind: "phone" },
    },
  ];

  test.each([
    ["a dialog with no question and no options", { id: "x", sessionId: "$1", waitingSince: "2026-09-08T10:00:00.000Z", evidence: { kind: "dialog" } }],
    [
      "an item with no duplicates array",
      {
        id: "x",
        sessionId: "$1",
        sessionName: "a",
        waitingSince: "2026-09-08T10:00:00.000Z",
        kind: "irreversible",
        evidence: { kind: "prose", excerpt: "e", why: "w" },
        answerability: { kind: "phone" },
      },
    ],
    [
      "an item with a kind this build does not know",
      {
        id: "x",
        sessionId: "$1",
        sessionName: "a",
        waitingSince: "2026-09-08T10:00:00.000Z",
        kind: "urgent",
        evidence: { kind: "prose", excerpt: "e", why: "w" },
        answerability: { kind: "phone" },
        duplicates: [],
      },
    ],
    [
      "a needs-a-screen answerability with no reason",
      {
        id: "x",
        sessionId: "$1",
        sessionName: "a",
        waitingSince: "2026-09-08T10:00:00.000Z",
        kind: "other",
        evidence: { kind: "prose", excerpt: "e", why: "w" },
        answerability: { kind: "needs-a-screen" },
        duplicates: [],
      },
    ],
    [
      "a duplicate with no waitingSince",
      {
        id: "x",
        sessionId: "$1",
        sessionName: "a",
        waitingSince: "2026-09-08T10:00:00.000Z",
        kind: "other",
        evidence: { kind: "prose", excerpt: "e", why: "w" },
        answerability: { kind: "phone" },
        duplicates: [{ sessionId: "$2", sessionName: "b" }],
      },
    ],
  ])("refuses %s", (_name, item) => {
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    raw["attention"] = { kind: "list", items: [item], sessionsScanned: 3, scannedAt: LIST.scannedAt };
    writeFileSync(path, JSON.stringify(raw, null, 2));

    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("the checkpoint must survive — the register is not regenerable");
    expect(read.checkpoint.attention.kind).toBe("unknown");
  });

  test("accepts a fully-formed item, so the parser is not just refusing everything", () => {
    // The positive control on the five refusals above. A parser that returned
    // `unknown` for every input would pass all of them and be useless.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("unreachable");
    expect(read.checkpoint.attention.kind).toBe("list");
    if (read.checkpoint.attention.kind !== "list") return;
    expect(read.checkpoint.attention.items).toHaveLength(1);
  });

  test("what survives the parser can always be rendered", () => {
    // The consequence Sol actually hit: `inboxLines()` threw. A parser is only
    // total if everything downstream of it can take what it emits.
    const root = tempRoot();
    const store = mustOpen(root);
    store.checkpoint({ lastGoodSnapshotAt: null, tick: true, attention: LIST });
    const path = join(root, CHECKPOINT_FILE);
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    raw["attention"] = {
      kind: "list",
      items: HALF_ITEMS,
      sessionsScanned: 3,
      scannedAt: LIST.scannedAt,
    };
    writeFileSync(path, JSON.stringify(raw, null, 2));
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("unreachable");
    expect(() => inboxLines(read.checkpoint.attention, Date.now())).not.toThrow();
  });
});

describe("the whole path: does the list actually reach current.json", () => {
  // THE STAGE'S "DONE", ASSERTED RATHER THAN ASSUMED. Everything else here tests
  // a piece of the path — the parser, the store, the pass — and every piece can
  // be green while the wiring between the daemon and the file is not. This runs
  // the real daemon against a scratch store with an injected source and an
  // injected runner, and reads the bytes back off disk.

  function abortAfter(ms: number): AbortController {
    const controller = new AbortController();
    setTimeout(() => controller.abort(), ms).unref?.();
    return controller;
  }

  async function heldOpen(signal: AbortSignal): Promise<void> {
    await new Promise<void>((resolve) => {
      if (signal.aborted) resolve();
      else signal.addEventListener("abort", () => resolve());
    });
  }

  test("a list produced by the pass is on disk when the daemon stops", async () => {
    const root = tempRoot();
    const controller = abortAfter(700);
    let passes = 0;
    await runOverseer({
      root,
      baseUrl: "http://127.0.0.1:1",
      signal: controller.signal,
      tickMs: 100,
      log: () => {},
      source: async function* () {
        await heldOpen(controller.signal);
      },
      attention: {
        intervalMs: 60,
        run: async () => {
          passes += 1;
          return LIST;
        },
      },
    });

    expect(passes).toBeGreaterThan(0);
    const read = readCheckpoint(root);
    expect(read.kind).toBe("checkpoint");
    if (read.kind !== "checkpoint") return;
    expect(read.checkpoint.attention).toEqual(LIST);
  });

  test("a daemon given no pass publishes `unknown`, not an empty list", async () => {
    // With no OPENROUTER_API_KEY the runner is absent, and this is what the page
    // then draws: *nothing has looked*, which is not *nothing needs you*.
    const root = tempRoot();
    const controller = abortAfter(400);
    await runOverseer({
      root,
      baseUrl: "http://127.0.0.1:1",
      signal: controller.signal,
      tickMs: 100,
      log: () => {},
      source: async function* () {
        await heldOpen(controller.signal);
      },
    });
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("expected a checkpoint");
    expect(read.checkpoint.attention.kind).toBe("unknown");
  });

  test("a pass that throws publishes `unknown`, not the last good list", async () => {
    // Leaving the previous list in place would go on publishing a fleet that was
    // true twenty minutes ago while the probe was broken, with its own
    // `scannedAt` the only clue and nobody reading it.
    const root = tempRoot();
    const controller = abortAfter(700);
    await runOverseer({
      root,
      baseUrl: "http://127.0.0.1:1",
      signal: controller.signal,
      tickMs: 100,
      log: () => {},
      source: async function* () {
        await heldOpen(controller.signal);
      },
      attention: {
        intervalMs: 60,
        run: async () => {
          throw new Error("tmux went away");
        },
      },
    });
    const read = readCheckpoint(root);
    if (read.kind !== "checkpoint") throw new Error("expected a checkpoint");
    expect(read.checkpoint.attention.kind).toBe("unknown");
    if (read.checkpoint.attention.kind !== "unknown") return;
    expect(read.checkpoint.attention.why).toContain("tmux went away");
  });

  test("two passes never overlap, however slow one is", async () => {
    // The pass makes paid calls and can outlive its own interval on a bad
    // afternoon at the gateway. Overlapping passes would double the bill and race
    // each other's memory file for no benefit at all.
    const root = tempRoot();
    const controller = abortAfter(700);
    let inFlight = 0;
    let overlapped = false;
    await runOverseer({
      root,
      baseUrl: "http://127.0.0.1:1",
      signal: controller.signal,
      tickMs: 100,
      log: () => {},
      source: async function* () {
        await heldOpen(controller.signal);
      },
      attention: {
        intervalMs: 30,
        run: async () => {
          inFlight += 1;
          if (inFlight > 1) overlapped = true;
          await new Promise((resolve) => setTimeout(resolve, 150));
          inFlight -= 1;
          return LIST;
        },
      },
    });
    expect(overlapped).toBe(false);
  });
});

describe("attentionNotYetRun", () => {
  test("carries the checkpoint's own instant and says that is what it is", () => {
    const list = attentionNotYetRun("2026-09-08T12:00:00.000Z");
    expect(list.kind).toBe("unknown");
    if (list.kind !== "unknown") return;
    expect(list.scannedAt).toBe("2026-09-08T12:00:00.000Z");
    expect(list.why).toContain("not when anything was scanned");
  });
});
