/* Generated by the shadcn CLI, then edited by hand — which is the shadcn model,
 * not a workaround: these files are source, not a dependency.
 *
 * TWO LOCAL EDITS, and `shadcn add` would silently undo both.
 *
 * ONE — the focus ring is drawn at full opacity, where upstream ships
 * `focus-visible:ring-ring/50`. Halved against this dark page the ring measures
 * 1.84:1, under the 3:1 WCAG asks of a focus indicator — and these components
 * suppress the browser's own 11.4:1 ring with `outline-none` in order to draw
 * their own. The token behind it is set in styles/tokens.css, which carries the
 * full reasoning.
 *
 * TWO — `outline` and `ghost` were repainted on 2026-08-27, because upstream's
 * dark branch is written for shadcn's palette and this app's is not. Both of
 * these are *our* decisions and the diff from upstream is small but load-bearing:
 *
 *   - `outline` shipped `dark:bg-input/30` over `bg-background` plus
 *     `shadow-xs`. Every `dark:` here means "always" (see the `@custom-variant`
 *     in tailwind.css), so on the shelf that rendered as a muddy translucent
 *     grey slab — measured `oklab(0.3 0 0 / 0.3)` — under a drop shadow at 5%
 *     black, which on a near-black page is nothing at all. It is the reason the
 *     page's *primary* action looked disabled. Now: a transparent face and a
 *     real border, so an outline button is an outline.
 *   - both hovered to `bg-accent`, and `--accent` in this app is a raised dark
 *     grey **surface**, not the orange (tokens.css shouts about that name).
 *     Meanwhile every hand-rolled control on the shelf — the chips, the card's
 *     icon buttons, Undo — hovers to `bg-highlight/10`. Two hover languages on
 *     one page. The orange one won, because it is the app's.
 *
 * If you re-run the CLI over this file, put the `/50` and both variants back in
 * the bin. `/design` draws every variant at once; look there afterwards. */

import type * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "tw:inline-flex tw:shrink-0 tw:items-center tw:justify-center tw:gap-2 tw:rounded-md tw:text-sm tw:font-medium tw:whitespace-nowrap tw:transition-all tw:outline-none tw:focus-visible:border-ring tw:focus-visible:ring-[3px] tw:focus-visible:ring-ring tw:disabled:pointer-events-none tw:disabled:opacity-50 tw:aria-invalid:border-destructive tw:aria-invalid:ring-destructive/20 tw:dark:aria-invalid:ring-destructive/40 tw:[&_svg]:pointer-events-none tw:[&_svg]:shrink-0 tw:[&_svg:not([class*=size-])]:size-4",
  {
    variants: {
      variant: {
        /* `brightness`, not `bg-primary/90`. An alpha of 90% composites the
           orange over whatever is behind it, and behind it is a near-black
           page — so the stock hover makes the button *darker*, which on a dark
           ground reads as pressed-and-stuck rather than as live. */
        default:
          "tw:bg-primary tw:text-primary-foreground tw:hover:brightness-110",
        destructive:
          "tw:bg-destructive tw:text-white tw:hover:bg-destructive/90 tw:focus-visible:ring-destructive/20 tw:dark:bg-destructive/60 tw:dark:focus-visible:ring-destructive/40",
        outline:
          "tw:border tw:border-border tw:bg-transparent tw:text-foreground tw:hover:border-highlight/60 tw:hover:bg-highlight/10 tw:hover:text-foreground",
        secondary:
          "tw:bg-secondary tw:text-secondary-foreground tw:hover:bg-secondary/80",
        ghost:
          "tw:text-muted-foreground tw:hover:bg-highlight/10 tw:hover:text-foreground",
        link: "tw:text-primary tw:underline-offset-4 tw:hover:underline",
      },
      size: {
        default: "tw:h-9 tw:px-4 tw:py-2 tw:has-[>svg]:px-3",
        xs: "tw:h-6 tw:gap-1 tw:rounded-md tw:px-2 tw:text-xs tw:has-[>svg]:px-1.5 tw:[&_svg:not([class*=size-])]:size-3",
        sm: "tw:h-8 tw:gap-1.5 tw:rounded-md tw:px-3 tw:has-[>svg]:px-2.5",
        lg: "tw:h-10 tw:rounded-md tw:px-6 tw:has-[>svg]:px-4",
        icon: "tw:size-9",
        "icon-xs": "tw:size-6 tw:rounded-md tw:[&_svg:not([class*=size-])]:size-3",
        "icon-sm": "tw:size-8",
        "icon-lg": "tw:size-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
