/**
 * **Builds the word list the shelf-topic chooser ships** —
 * src/shelf-terms/data/glasgow-norms.ts — from the published file, which is
 * downloaded by hand and never committed:
 *
 *     npx tsx scripts/build-word-lists.ts <dir>
 *
 * `<dir>` holds `glasgow-norms.csv` — save the Glasgow Norms (Scott et al.
 * 2019) supplementary file `13428_2018_1099_MOESM2_ESM.csv` under this name;
 * download it from https://link.springer.com/article/10.3758/s13428-018-1099-3
 *
 * Licence and credit: src/shelf-terms/data/ATTRIBUTION.md, which also says
 * why SUBTLEX-US, tried first, is not shipped. Why the list and the rule that
 * reads it: docs/plans/260929a-shelf-topics-round-three-concreteness-zero-pills-archived-toggle.md.
 *
 * The output is TypeScript, not JSON read at run time, so the serverless
 * bundle carries it with no file-system read; it is one string per
 * concreteness bucket, split once on first use, to stay small.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
if (!dir) {
  console.error("Usage: npx tsx scripts/build-word-lists.ts <dir holding glasgow-norms.csv>");
  process.exit(1);
}
const out = join(import.meta.dirname, "..", "src", "shelf-terms", "data");
const WORD = /^[a-z][a-z'-]*$/;

/** A tiny CSV reader: the Glasgow file has no quoted fields. */
const rows = readFileSync(join(dir, "glasgow-norms.csv"), "latin1").split(/\r?\n/);
const header = rows[0]?.split(",") ?? [];
const cnc = header.indexOf("CNC");
const fam = header.indexOf("FAM");
if (header[0] !== "Words" || cnc < 0 || fam < 0) throw new Error("glasgow-norms.csv: unexpected header");

/** word → [concreteness, familiarity], each the mean on 1–7, one decimal */
const ratings = new Map<string, [number, number]>();
const scale = (cells: string[], at: number, word: string): number => {
  const mean = Number(cells[at]);
  if (!Number.isFinite(mean) || mean < 1 || mean > 7) throw new Error(`glasgow: bad ${header[at]} for ${word}`);
  return Math.round(mean * 10) / 10;
};
for (const line of rows.slice(2)) {
  const cells = line.split(",");
  const word = cells[0]?.trim().toLowerCase() ?? "";
  /* "bank (river)" rates one sense; the bare "bank" row rates the word as a
     reader meets it without context, which is how a topic chip meets them. */
  if (!WORD.test(word)) continue;
  ratings.set(word, [scale(cells, cnc, word), scale(cells, fam, word)]);
}

/* Bucketed by concreteness; each word carries its familiarity × 10 as two
   trailing digits ("abbey59" … familiarity 5.9). */
const byConcreteness = new Map<string, string[]>();
for (const [word, [c, f]] of [...ratings].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
  const key = c.toFixed(1);
  byConcreteness.set(key, [...(byConcreteness.get(key) ?? []), `${word}${Math.round(f * 10)}`]);
}
const buckets = [...byConcreteness]
  .sort((a, b) => Number(a[0]) - Number(b[0]))
  .map(([r, words]) => `  "${r}": "${words.join(" ")}",`)
  .join("\n");

writeFileSync(
  join(out, "glasgow-norms.ts"),
  `/**
 * GENERATED by scripts/build-word-lists.ts — do not edit by hand.
 *
 * Concreteness and familiarity from the Glasgow Norms (Scott, Keitel,
 * Becirspahic, Yao & Sereno, 2019), CC BY 4.0: src/shelf-terms/data/ATTRIBUTION.md.
 * Each is the mean rating on the norms' 1–7 scale (abstract → concrete,
 * unfamiliar → familiar), rounded to one decimal, for the ${ratings.size} single words
 * the norms rate without a sense given. Keyed by concreteness; each word ends
 * in its familiarity × 10.
 */
const BY_CONCRETENESS: Record<string, string> = {
${buckets}
};

export interface GlasgowRating {
  concreteness: number;
  familiarity: number;
}

let table: Map<string, GlasgowRating> | undefined;

/** The word's Glasgow ratings, or undefined when the norms do not rate it. */
export function glasgowRating(word: string): GlasgowRating | undefined {
  if (!table) {
    table = new Map();
    for (const [concreteness, words] of Object.entries(BY_CONCRETENESS))
      for (const w of words.split(" "))
        table.set(w.slice(0, -2), { concreteness: Number(concreteness), familiarity: Number(w.slice(-2)) / 10 });
  }
  return table.get(word);
}
`,
);

console.log(`glasgow-norms.ts: ${ratings.size} words, ${byConcreteness.size} concreteness buckets`);
