/**
 * The homepage: the shelf of articles, and everything above it — the search
 * box, the sort chips, the view toggle, the box for adding one.
 *
 * Greg, 2026-08-25:
 *
 * > have a homepage that enables us to browse past documents, and then if I
 * > click on one of the documents, it takes us to this interface that we've been
 * > building using a slug of the URL
 *
 * A card is a *decision aid*, not a summary — you are choosing what to read, and
 * the thing that decides it is what the piece says and how long it will take.
 * So the blurb is the tree root's gist: one sentence about the whole article,
 * generated by the same pass that fills the L0 column. That is the product's own
 * idea turned on its own library, and it costs nothing because the sentence
 * already exists. See docs/project/library.md.
 *
 * ## What this file is now, and what it is not
 *
 * It is **the page**: the fetch, the URL state, and the four narrowings that
 * turn a list of articles into the list on screen. It is deliberately not the
 * things it draws. Since 2026-08-26 the shelf has two renderers rather than
 * one, and everything they share had to stop living inside one of them:
 *
 * | File | What |
 * |---|---|
 * | lib/DataTable.tsx | **reusable**: the chips, the dense table, the TanStack options that are decisions |
 * | lib/table-sort.ts | **reusable**: sorting state ⇄ URL, the collator, `sinkLast` |
 * | library-columns.tsx | what the shelf can be sorted by, and how each column draws |
 * | ShelfControls.tsx | the two controls that are the shelf's own: Unread, cards-or-table |
 * | ShelfEntry.tsx | the card, the five buttons, rename-in-place, the tooltip |
 *
 * **One sort state, two renderers**, which is the shape Greg asked for when he
 * said he liked the cards and wanted them sortable anyway. The order, the
 * filter and the search are all resolved here, above the branch, so the two
 * views cannot disagree about what is on the shelf.
 *
 * Styled with Tailwind utilities rather than a block in styles.css, and that is
 * the rule rather than a preference: this page is chrome, and chrome is what
 * shadcn and Tailwind were adopted for
 * (docs/project/web-client.md#tailwind-and-shadcn-components). The reading view
 * stays hand-written, because its geometry is not something utilities can say.
 * Note the `tw:` prefix on every class — unprefixed names do nothing here.
 *
 * See docs/plans/library-shelf-actions-and-search.md and
 * docs/plans/library-sorting.md.
 */
import { useCallback, useEffect, useMemo, useState } from "react";
import { throttle, useQueryState } from "nuqs";
import type { OnChangeFn, SortingState } from "@tanstack/react-table";
import { functionalUpdate } from "@tanstack/react-table";
import { ChevronRight, Palette, Search, Undo2, User, X } from "lucide-react";
import type { LibraryEntry, LibraryHit } from "../types.js";
import { AddArticle } from "./AddArticle.js";
import { ADDED_NOTE, CARD_NOTES, CHIP_ORDER, DEFAULT_BY, libraryColumns } from "./library-columns.js";
import { DataTable, naturalDirections, useSortedTable } from "./lib/DataTable.js";
import { isAllNatural, sinkLast, sortingFromUrl, sortingToUrl } from "./lib/table-sort.js";
import { Link } from "./Link.js";
import { fold, foldWithMap, libraryHitHref, queryTerms } from "./library-hits.js";
import {
  libraryByParam,
  libraryDirParam,
  libraryQueryParam,
  libraryShowParam,
  libraryViewParam,
} from "./params.js";
import { pageTitle, useDocumentTitle } from "./page-title.js";
import { DESIGN_HREF } from "./router.js";
import { ShelfCard } from "./ShelfEntry.js";
import { ShelfControls, type ShelfFilter } from "./ShelfControls.js";
import { useJobs } from "./useJobs.js";
import { useLibrarySearch } from "./useLibrarySearch.js";
import { useNow } from "./useNow.js";
import { useShelf } from "./useShelf.js";
import { useSlow } from "./useSlow.js";
import { useRenderCount } from "./perf.js";

export function Library() {
  useRenderCount("Library");
  const shelf = useShelf();
  const { articles, error, reload } = shelf;
  const slow = useSlow(articles === null);

  /* Every one of these is in the URL rather than in `useState`, which is the
     rule the whole app runs on (docs/project/url-state.md): reload the
     homepage, or send somebody the link, and you get the same shelf back.
     Until 2026-08-26 the search box was `useState` and the order was whatever
     the server happened to send, so neither survived a reload. */
  const [rawQuery, setQuery] = useQueryState("q", libraryQueryParam);
  const [by, setBy] = useQueryState("by", libraryByParam);
  const [rawDir, setDir] = useQueryState("dir", libraryDirParam);
  const [view, setView] = useQueryState("view", libraryViewParam);
  const [show, setShow] = useQueryState("show", libraryShowParam);

  const query = rawQuery ?? "";

  /* The tab. Bare, this is the homepage and so the one page that leads with the
     app's own name; narrow the shelf and what you narrowed it to takes the
     front instead. See src/web/page-title.ts. */
  useDocumentTitle(pageTitle({ kind: "library", query, unread: show === "unread" }));
  /* No `dir` in the URL means "each key goes whichever way it naturally goes",
     which is a different answer per column — so this stays an empty list rather
     than a default, and `sortingFromUrl` fills the gaps. See params.ts, where
     giving it a default was briefly a bug. */
  const dir = rawDir ?? [];

  /**
   * Make a `push` change to the view, taking any half-typed search with it.
   *
   * `?q=` is written on a 200ms debounce, so a click landing inside that window
   * pushes a history entry that does not have the query in it yet — and the
   * query then *replaces* itself into the new entry a moment later. Back then
   * undoes the sort **and** the search together, having appeared to record only
   * the sort. Writing `q` here with the limit lifted puts it in the same batch
   * as the push, so one entry carries both. nuqs queues every synchronous write
   * until the next tick and flushes them as one URL update, which is also why
   * `setBy` and `setDir` are one history entry rather than two.
   *
   * Caught by a cross-family review, 2026-08-26.
   */
  const pushView = useCallback(
    (write: () => void) => {
      write();
      void setQuery(query || null, { limitUrlUpdates: throttle(0) });
    },
    [query, setQuery],
  );

  /* One clock reading, re-read once a minute and handed to everything that
     prints a relative date — see useNow.ts for both halves of why. */
  const now = useNow();

  const columns = useMemo(() => libraryColumns(shelf, now), [shelf, now]);
  const natural = useMemo(() => naturalDirections(columns), [columns]);
  /* `DEFAULT_BY` as the fallback: a URL naming nothing we recognise lands on
     the ordinary shelf rather than on an unsorted list with no chip pressed. */
  const sorting = useMemo(
    () => sortingFromUrl(by, dir, natural, DEFAULT_BY),
    [by, dir, natural],
  );

  /* Matcher one: the shelf itself, filtered in the browser, then narrowed by
     the Unread chip. The *order* is no longer ours — TanStack owns it below —
     but which rows exist still is.

     `useMemo` because this runs on every keystroke over every article, and
     because the identity of the array it returns is what decides whether the
     whole table is rebuilt. */
  const rows = useMemo(() => {
    if (!articles) return null;
    const found = filterEntries(articles, query);
    return show === "unread" ? found.filter((a) => a.opens === 0) : found;
  }, [articles, query, show]);

  /**
   * The sorting state, written straight back to the address bar.
   *
   * TanStack hands us an updater rather than a value — it computes what a click
   * means, including which end a new column starts at and whether shift was
   * held — so this applies it to the current state and serialises the result.
   * That is the whole of what replaced a hand-written `nextSort`.
   */
  const onSortingChange = useCallback<OnChangeFn<SortingState>>(
    (updater) => {
      /* Applied to `sorting` — the very array TanStack was handed as its state,
         so what it computed the update against and what we apply it to cannot
         be two different things. */
      const next = functionalUpdate(updater, sorting);
      /* Never empty. `enableSortingRemoval: false` should make that impossible,
         but an empty sort would fall back to whatever order the data arrived
         in — a state the reader cannot name or ask for — so it is refused here
         as well as configured against. */
      if (next.length === 0) return;
      const url = sortingToUrl(next);
      pushView(() => {
        void setBy(url.by);
        /* Left out when it says nothing the columns would not have said
           themselves, which keeps `?by=title` short — and correct, since an
           absent `dir` is what makes the per-column fallback run at all. */
        void setDir(isAllNatural(next, natural) ? null : url.dir);
      });
    },
    [sorting, natural, pushView, setBy, setDir],
  );

  const table = useSortedTable({
    data: rows ?? EMPTY,
    columns,
    sorting,
    onSortingChange,
    rowId: slugOf,
  });

  /* The fixture last, in every order and both directions. It is a committed
     placeholder rather than something the reader added, and the server has
     always kept it at the foot of the shelf — sorting in the browser without
     carrying that over puts a demo excerpt above the reader's own library the
     first time anybody sorts by length. */
  const modelRows = table.getRowModel().rows;
  const primary = sorting[0]?.id;
  const sorted = useMemo(() => {
    /* Two sinks, in this order.

       **Missing values last, whichever way the arrow points.** `sortUndefined`
       is the option for this and it is switched off, because TanStack gets it
       wrong when two values are both missing — see lib/table-sort.ts §
       numberOrMissing. So the columns sort missing *low*, consistently, and the
       rows whose primary key is missing are moved down here. Ascending by "last
       opened" must not fill the top of the shelf with everything you have never
       opened: that is a useful thing to want, and it is what the Unread chip is
       for.

       **Then the fixture**, below even those. It is a committed placeholder
       rather than something the reader added, and the server has always kept it
       at the foot of the shelf. */
    const missingLast = primary
      ? sinkLast(modelRows, (r) => r.getValue(primary) === undefined)
      : modelRows;
    return sinkLast(missingLast, (r) => !!r.original.fixture);
  }, [modelRows, primary]);

  // Reload the shelf the moment a job finishes, rather than telling the reader
  // to reload the page — they just watched the five steps go green, and an
  // empty shelf underneath would read as a failure.
  const queue = useJobs(reload);

  // Matcher two: the passages inside the articles, from the server.
  const passages = useLibrarySearch(query);

  const searching = query.trim().length > 0;
  const total = articles?.length ?? 0;
  const showing = rows?.length ?? 0;
  // Said only when something is actually being hidden. "12 of 12" is noise.
  const narrowed = (searching || show === "unread") && showing !== total;

  /* The slugs the Unread chip lets through, whatever the search box says — the
     passages are the answer to the search, so narrowing them by the search
     twice would be wrong. `null` when the chip is off, which is "do not narrow"
     rather than "narrow to nothing". */
  const unread = useMemo(
    () =>
      show === "unread" && articles
        ? new Set(articles.filter((a) => a.opens === 0).map((a) => a.slug))
        : null,
    [articles, show],
  );

  /* Whichever column is sorted first decides what a card says about itself. */
  const note = CARD_NOTES[sorting[0]?.id ?? ""] ?? ADDED_NOTE;

  return (
    <main className="tw:mx-auto tw:max-w-4xl tw:px-6 tw:py-10 tw:font-sans">
      <header className="tw:mb-8">
        {/* The design reference sits on the masthead line rather than under the
            strapline, and is deliberately the quietest thing on the page: it is
            developer furniture, and a reader arriving at their shelf should not
            have to step over it. Same faint-until-hovered treatment as the
            back-link in Masthead.tsx, so the two read as one convention. */}
        <div className="tw:flex tw:items-baseline tw:justify-between tw:gap-4">
          <h1 className="tw:font-prose tw:text-3xl tw:text-foreground">Spideryarn</h1>
          <div className="tw:flex tw:items-baseline tw:gap-4">
            {/* Home is where a global thing gets a way in. The profile page
                holds what is true of the reader on every article, so a link to
                it from inside one article would be a link nobody finds —
                docs/project/reader-profile.md. Before Design because it is for
                the reader and Design is developer furniture. */}
            <Link
              href="/profile"
              className="tw:inline-flex tw:items-center tw:gap-1.5 tw:text-xs tw:text-ink-faint tw:no-underline tw:hover:text-highlight"
              title="What the model knows about who it is writing for"
            >
              <User size={13} />
              You
            </Link>
            <Link
              href={DESIGN_HREF}
              className="tw:inline-flex tw:items-center tw:gap-1.5 tw:text-xs tw:text-ink-faint tw:no-underline tw:hover:text-highlight"
              title="Every token, face and component variant on one page — look here after changing tokens.css"
            >
              <Palette size={13} />
              Design
            </Link>
          </div>
        </div>
        <p className="tw:mt-1 tw:text-sm tw:text-muted-foreground">
          Read deeply, at whatever level of detail you need. Pick a piece.
        </p>
      </header>

      {/* `trim()` rather than `v || null`: spaces alone serialise to `?q=%20`,
          which the parser reads back as `null`. So the box emptied itself on
          reload while the URL still carried something — the one thing this
          page's URL state is supposed to make impossible. A value that merely
          *ends* in a space is kept as typed. */}
      <SearchBox value={query} onChange={(v) => void setQuery(v.trim() ? v : null)} />

      <AddArticle queue={queue} />

      {error && (
        <p className="tw:rounded-md tw:border tw:border-destructive/40 tw:bg-destructive/10 tw:p-4 tw:text-sm tw:text-foreground">
          {error}
        </p>
      )}
      {shelf.actionError && (
        <p className="tw:mb-3 tw:rounded-md tw:border tw:border-destructive/40 tw:bg-destructive/10 tw:px-4 tw:py-2 tw:text-sm tw:text-foreground">
          {shelf.actionError}
        </p>
      )}

      {shelf.undoable && (
        <UndoStrip title={shelf.undoable.title} onUndo={() => void shelf.undo()} />
      )}

      {/* The controls sit directly above the list they govern, and only once
          there is a list. A sort control over an empty shelf is furniture. */}
      {total > 0 && (
        <ShelfControls
          table={table}
          chipOrder={CHIP_ORDER}
          view={view}
          onView={(v) => pushView(() => void setView(v))}
          filter={show}
          onFilter={(f) => pushView(() => void setShow(f))}
        />
      )}

      {narrowed && (
        <p className="tw:mb-3 tw:mt-0 tw:text-xs tw:text-muted-foreground">
          {showing} of {total} {total === 1 ? "article" : "articles"}
        </p>
      )}

      {/* Silent until the wait is worth mentioning — on a warm shelf this fetch
          is over well before that, and a line that flashes up and away reads as
          a fault. After that, say what is being fetched. See useSlow.ts, which
          owns the threshold. */}
      {!error && articles === null && slow && (
        <p className="tw:text-sm tw:text-muted-foreground">Reading the shelf…</p>
      )}
      {articles?.length === 0 && (
        <p className="tw:text-sm tw:text-muted-foreground">
          Nothing on the shelf yet. Paste a URL above and it'll be here in a minute or two.
        </p>
      )}
      {showing === 0 && total > 0 && (
        <p className="tw:text-sm tw:text-muted-foreground">{nothingLeft(query, show)}</p>
      )}

      {/* One list, two renderers. The sort, the filter and the search are all
          resolved above this line, so neither view can disagree with the other
          about what is on the shelf or what order it is in — see
          ShelfControls.tsx. */}
      {sorted.length > 0 && view === "table" && (
        <DataTable table={table} rows={sorted} caption="Your articles" />
      )}
      {sorted.length > 0 && view === "cards" && (
        <ul className="tw:m-0 tw:flex tw:list-none tw:flex-col tw:gap-3 tw:p-0">
          {sorted.map((row) => (
            <li key={row.id}>
              <ShelfCard entry={row.original} shelf={shelf} note={note(row.original, now)} />
            </li>
          ))}
        </ul>
      )}

      {/* The passages obey the Unread chip too. Without that, turning Unread on
          and searching for something only an opened article contains printed
          "No unopened article matches …" and then listed passages from that
          very article — two answers to one question, on one screen. The hidden
          ones are counted rather than silently dropped, because "it is in
          something you have already read" is the useful half of that answer. */}
      {searching && <Passages state={passages} query={query} only={unread} />}

      {!searching && <Archived shelf={shelf} />}
    </main>
  );
}

/**
 * Why nothing is on screen.
 *
 * A shelf with articles on it and nothing matching is a different thing from an
 * empty shelf, and it has to say **which** of the two narrowings emptied it —
 * otherwise pressing Unread on a shelf you have read all of looks like the
 * search box has broken.
 */
function nothingLeft(query: string, show: ShelfFilter): string {
  const q = query.trim();
  if (q && show === "unread") return `No unopened article matches “${q}”.`;
  if (q) return `No article's title, author or blurb matches “${q}”.`;
  return "You have opened all of them.";
}

/** Stable identity, and — see lib/DataTable.tsx — the tiebreak behind every sort. */
const slugOf = (entry: LibraryEntry) => entry.slug;

/** One frozen empty array, so a shelf that has not loaded does not rebuild the table each render. */
const EMPTY: LibraryEntry[] = [];

/* ------------------------------------------------------------- searching -- */

/**
 * The cards whose visible words contain every term typed.
 *
 * AND across terms, substring within one — so "seth noema" finds the article by
 * that author on that site, and "consc" finds "consciousness" while you are
 * still typing it. Deliberately over exactly the four fields a card renders:
 * matching something invisible would look like a bug from the outside.
 */
function filterEntries(articles: LibraryEntry[], query: string): LibraryEntry[] {
  const terms = queryTerms(query);
  if (terms.length === 0) return articles;
  return articles.filter((a) => {
    const hay = fold([a.title, a.byline, a.siteName, a.gist].filter(Boolean).join(" "));
    return terms.every((t) => hay.includes(t));
  });
}

function SearchBox({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  return (
    <div className="tw:mb-4">
      <div className="tw:relative">
        <Search
          size={15}
          className="tw:pointer-events-none tw:absolute tw:left-3 tw:top-1/2 tw:-translate-y-1/2 tw:text-muted-foreground"
        />
        <input
          type="search"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder="Search titles, authors, and the text of every article"
          aria-label="Search the library"
          /* A ring as well as a border colour on focus. A 1px border changing
             from grey to orange is about one pixel's worth of colour on a
             near-black page, which is not enough to find the box you have just
             tabbed into — and this input suppresses the browser's own ring
             with `outline-none`, so nothing else was drawing one. Same
             treatment on the URL box in AddArticle.tsx. */
          className="tw:w-full tw:rounded-lg tw:border tw:border-border tw:bg-card tw:py-2 tw:pl-9 tw:pr-9 tw:text-sm tw:text-foreground tw:transition-colors tw:outline-none tw:placeholder:text-muted-foreground tw:focus:border-highlight tw:focus:ring-2 tw:focus:ring-highlight/25"
        />
        {value && (
          <button
            type="button"
            onClick={() => onChange("")}
            aria-label="Clear the search"
            className="tw:absolute tw:right-2 tw:top-1/2 tw:inline-flex tw:size-7 tw:-translate-y-1/2 tw:items-center tw:justify-center tw:rounded-md tw:text-muted-foreground tw:transition-colors tw:hover:bg-highlight/10 tw:hover:text-foreground"
          >
            <X size={14} />
          </button>
        )}
      </div>
    </div>
  );
}

/**
 * The passages, under the cards.
 *
 * Under rather than beside, and after rather than before, because the cards are
 * the answer to "which of my articles is this?" and the passages are the answer
 * to "where in them?". The first question is the commoner one and the free one.
 */
function Passages({
  state,
  query,
  only,
}: {
  state: ReturnType<typeof useLibrarySearch>;
  query: string;
  /**
   * The slugs the Unread chip is letting through, or `null` for "everything".
   *
   * Narrowing happens **here rather than in the request**, and that has a cost
   * worth stating: the server caps the list before we see it, so a query whose
   * best hits are all in articles you have read can come back with nothing left
   * for this to show even though matches exist. That is the same trap
   * `excludeSlug` exists to avoid for chat's `search_library`
   * (docs/project/chat-tools.md). It is acceptable here and not there because
   * the reader can see the chip they pressed, and the line below says how many
   * were hidden — a caller reporting "found nothing" cannot do either.
   */
  only: Set<string> | null;
}) {
  if (state.error) {
    return (
      <p className="tw:mt-8 tw:text-sm tw:text-muted-foreground">
        Couldn't search the text of the articles: {state.error}
      </p>
    );
  }
  if (state.searching && state.hits.length === 0) {
    return <p className="tw:mt-8 tw:text-sm tw:text-muted-foreground">Searching the text…</p>;
  }
  if (!state.asked) return null;
  /* Results are shown only for the query they are the answer to. Without this
     the previous query's passages sit on screen while the next request runs,
     marked and linked with the NEW query — passages that do not contain what
     the reader typed, presented as though they do. */
  if (state.resultsQuery !== query.trim()) return null;
  if (state.hits.length === 0) {
    return (
      <p className="tw:mt-8 tw:text-sm tw:text-muted-foreground">
        Nothing in the text of any article matches “{query.trim()}”.
      </p>
    );
  }

  const hits = only ? state.hits.filter((h) => only.has(h.slug)) : state.hits;
  const hidden = state.hits.length - hits.length;
  /* Counted here rather than read from `state.articles`, which is the server's
     count over the hits it sent (`new Set(hits.map(h => h.slug)).size` in
     routes.ts — the same expression). It has to be the count of what is *shown*
     once the Unread chip can remove some, and the two agree exactly when
     nothing is removed. */
  const articles = new Set(hits.map((h) => h.slug)).size;

  /* Counted, never silently dropped: "it is in something you have already read"
     is the useful half of the answer, and a list that just came up empty with
     no explanation reads as a broken search. */
  const alsoIn = hidden > 0 && (
    <p className="tw:mt-2 tw:mb-0 tw:text-xs tw:text-muted-foreground">
      {hidden} more {hidden === 1 ? "passage is" : "passages are"} in articles you have already
      opened.
    </p>
  );

  if (hits.length === 0) {
    return (
      <section className="tw:mt-8">
        <p className="tw:m-0 tw:text-sm tw:text-muted-foreground">
          Nothing in an unopened article matches “{query.trim()}”.
        </p>
        {alsoIn}
      </section>
    );
  }

  return (
    <section className="tw:mt-8">
      <h2 className="tw:m-0 tw:mb-3 tw:text-xs tw:font-medium tw:tracking-wide tw:text-muted-foreground tw:uppercase">
        {hits.length} {hits.length === 1 ? "passage" : "passages"} in {articles}{" "}
        {articles === 1 ? "article" : "articles"}
        {/* Said out loud rather than silently truncated: a capped list that does
            not admit it reads as "that is everything". */}
        {state.capped && <span className="tw:ml-1 tw:normal-case">(showing the best)</span>}
      </h2>
      <ul className="tw:m-0 tw:flex tw:list-none tw:flex-col tw:gap-2 tw:p-0">
        {hits.map((hit) => (
          <li key={`${hit.slug}/${hit.blockId}`}>
            <Passage hit={hit} query={query} />
          </li>
        ))}
      </ul>
      {alsoIn}
    </section>
  );
}

/** How much of the paragraph to show. Wide enough to judge, short enough to skim. */
const SNIPPET_CHARS = 200;

function Passage({ hit, query }: { hit: LibraryHit; query: string }) {
  /* The four parameters this link must carry, and why dropping any one of them
     fails silently, are documented on `libraryHitHref` — a pure function in a
     module of its own precisely so that rule can be tested. It lost one of the
     four while it lived inline here, and the symptom was a link whose every
     present parameter was correct and which highlighted nothing. */
  const href = libraryHitHref(hit, query);

  return (
    <Link
      href={href}
      className="tw:block tw:rounded-md tw:border tw:border-border tw:bg-card tw:px-4 tw:py-3 tw:no-underline tw:hover:border-highlight/60"
    >
      <span className="tw:block tw:text-xs tw:text-muted-foreground">{hit.title}</span>
      <span className="tw:mt-1 tw:block tw:font-prose tw:text-[0.95rem] tw:leading-relaxed tw:text-foreground">
        {marked(hit.text, query)}
      </span>
    </Link>
  );
}

/**
 * A window of the paragraph around the first match, with the match in bold.
 *
 * The cutting and the marking happen here rather than on the server because the
 * two stores would do them differently — Postgres knows which *stems* matched,
 * not which characters — and two flavours of highlighting to reconcile is worse
 * than one that occasionally shows the start of the paragraph instead. See
 * `LibraryHit.text`.
 *
 * A stemmed hit is exactly that case: Postgres can match "qualias" for a search
 * for "qualia", and this will not find those letters. It falls back to the
 * opening of the paragraph, which is honest and readable rather than empty.
 */
function marked(text: string, query: string) {
  const terms = queryTerms(query);
  const { folded, starts, ends } = foldWithMap(text);

  let at = -1;
  let length = 0;
  for (const term of terms) {
    const i = folded.indexOf(term);
    if (i !== -1 && (at === -1 || i < at)) {
      at = i;
      length = term.length;
    }
  }

  // Nothing to point at — a stemmed match, or a term shorter than two
  // characters. Show the opening of the paragraph, which is honest and
  // readable rather than empty.
  if (at === -1) {
    const head = text.slice(0, SNIPPET_CHARS);
    return head.length < text.length ? `${head}…` : head;
  }

  /* Every offset is translated before it touches `text`, so the snippet carries
     the article's own punctuation — and the END comes from `ends`, which is the
     exclusive end of the source character the match finished inside. See
     `foldWithMap`. */
  const start = starts[at] ?? 0;
  const end = ends[at + length - 1] ?? text.length;
  const want = Math.max(0, SNIPPET_CHARS - (end - start));
  const from = Math.max(0, start - Math.floor(want / 2));
  const to = Math.min(text.length, end + (want - (start - from)));

  return (
    <>
      {from > 0 && "…"}
      {text.slice(from, start)}
      <strong className="tw:font-semibold tw:text-highlight">{text.slice(start, end)}</strong>
      {text.slice(end, to)}
      {to < text.length && "…"}
    </>
  );
}

/* ------------------------------------------------------------- archived --- */

/**
 * The other half of the shelf, behind a disclosure.
 *
 * Without this, Delete is **permanent from the interface**: the Undo strip is
 * gone after nine seconds and there is no other way back to an archived
 * article. Greg chose "archive, with an Undo" over a real delete precisely so
 * that nothing is destroyed — and an archive nobody can open is destruction
 * with extra steps. The plan deferred this ("a separate 'Show archived' view
 * can come later"); a cross-family review pointed out that "later" left the
 * feature contradicting its own reason for existing.
 *
 * Closed by default, and it does not fetch until opened: most sessions never
 * archive anything, and a request per homepage load to say "nothing here" is a
 * request nobody asked for. Hidden entirely while searching, because the search
 * deliberately does not look in here.
 */
function Archived({ shelf }: { shelf: ReturnType<typeof useShelf> }) {
  const [open, setOpen] = useState(false);
  const { archived, loadArchived } = shelf;

  /* An effect rather than a call in the click handler, because the list is also
     invalidated from *outside* this component: archiving or restoring sets it
     back to null, and with the fetch living in the handler an open panel then
     sat on "Looking…" for ever, waiting for a click that had already happened.
     Keyed on "open and we have nothing", so it covers both cases with one rule.
     Found in a browser pass, 2026-08-26. */
  useEffect(() => {
    if (open && archived === null) void loadArchived();
  }, [open, archived, loadArchived]);

  return (
    <section className="tw:mt-10">
      {/* A chevron, because this is a disclosure and nothing else said so — the
          words alone changed from "Show" to "Hide", and that was the only thing
          that moved. `-ml-2` keeps the *text* on the page's left margin while
          the hit area extends past it, so giving it padding did not shunt the
          label right. */}
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="tw:-ml-2 tw:inline-flex tw:h-7 tw:items-center tw:gap-1.5 tw:rounded-md tw:bg-transparent tw:px-2 tw:text-xs tw:text-muted-foreground tw:transition-colors tw:hover:bg-highlight/10 tw:hover:text-foreground"
      >
        <ChevronRight
          size={13}
          className={`tw:transition-transform ${open ? "tw:rotate-90" : ""}`}
        />
        {open ? "Hide deleted" : "Show deleted"}
      </button>

      {open && archived === null && (
        <p className="tw:mt-2 tw:text-sm tw:text-muted-foreground">Looking…</p>
      )}
      {open && archived?.length === 0 && (
        <p className="tw:mt-2 tw:text-sm tw:text-muted-foreground">Nothing deleted.</p>
      )}
      {open && !!archived?.length && (
        <ul className="tw:m-0 tw:mt-3 tw:flex tw:list-none tw:flex-col tw:gap-2 tw:p-0">
          {archived.map((a) => (
            <li
              key={a.slug}
              className="tw:flex tw:items-center tw:gap-3 tw:rounded-md tw:border tw:border-border tw:px-4 tw:py-2 tw:text-sm"
            >
              <span className="tw:min-w-0 tw:flex-1 tw:truncate tw:text-muted-foreground">
                {a.title}
              </span>
              <button
                type="button"
                onClick={() => void shelf.restore(a.slug)}
                className="tw:inline-flex tw:h-7 tw:shrink-0 tw:items-center tw:gap-1.5 tw:rounded-md tw:px-2.5 tw:text-xs tw:text-highlight tw:transition-colors tw:hover:bg-highlight/10"
              >
                <Undo2 size={14} />
                Put back
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

/* ----------------------------------------------------------------- undo --- */

function UndoStrip({ title, onUndo }: { title: string; onUndo: () => void }) {
  return (
    <div
      /* `status`, not `alert`: a screen reader should hear this when it gets to
         it rather than have the current sentence interrupted. Deleting was the
         reader's own act, so it is a confirmation, not an emergency. */
      role="status"
      className="tw:mb-3 tw:flex tw:items-center tw:gap-3 tw:rounded-md tw:border tw:border-border tw:bg-card tw:px-4 tw:py-2 tw:text-sm tw:text-foreground"
    >
      <span className="tw:min-w-0 tw:flex-1 tw:truncate">Deleted “{title}”</span>
      <button
        type="button"
        onClick={onUndo}
        className="tw:inline-flex tw:h-7 tw:shrink-0 tw:items-center tw:gap-1.5 tw:rounded-md tw:px-2.5 tw:text-xs tw:text-highlight tw:transition-colors tw:hover:bg-highlight/10"
      >
        <Undo2 size={14} />
        Undo
      </button>
    </div>
  );
}
