/**
 * The homepage: the shelf of articles, and the way to put another one on it.
 *
 * Greg, 2026-08-25:
 *
 * > have a homepage that enables us to browse past documents, and then if I
 * > click on one of the documents, it takes us to this interface that we've been
 * > building using a slug of the URL
 *
 * A card is a *decision aid*, not a summary — you are choosing what to read, and
 * the thing that decides it is what the piece says and how long it will take.
 * So the blurb is the tree root's gist: one sentence about the whole article,
 * generated by the same pass that fills the L0 column. That is the product's own
 * idea turned on its own library, and it costs nothing because the sentence
 * already exists. See docs/project/library.md.
 *
 * Styled with Tailwind utilities rather than a block in styles.css, and that is
 * the rule rather than a preference: this page is chrome, and chrome is what
 * shadcn and Tailwind were adopted for
 * (docs/project/web-client.md#tailwind-and-shadcn-components). The reading view
 * stays hand-written, because its geometry is not something utilities can say.
 * Note the `tw:` prefix on every class — unprefixed names do nothing here.
 */
import { useCallback, useEffect, useState } from "react";
import { FileText, MessageCircle } from "lucide-react";
import type { LibraryEntry } from "../types.js";
import { AddArticle } from "./AddArticle.js";
import { Link } from "./Link.js";
import { readHref } from "./router.js";
import { useJobs } from "./useJobs.js";

export function Library() {
  const [articles, setArticles] = useState<LibraryEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    fetch("/api/library")
      .then(async (r) => {
        const body = await r.json();
        if (!r.ok) throw new Error(body.error ?? r.statusText);
        return body as { articles: LibraryEntry[] };
      })
      .then((b) => setArticles(b.articles))
      // A fetch that never reached the server says "Failed to fetch", which
      // tells the reader nothing. Say the likely cause.
      .catch((e: Error) =>
        setError(
          e.message === "Failed to fetch"
            ? "Couldn't reach the server — is `npm run dev` still running?"
            : e.message,
        ),
      );
  }, []);

  useEffect(load, [load]);

  // Reload the shelf the moment a job finishes, rather than telling the reader
  // to reload the page — they just watched the five steps go green, and an
  // empty shelf underneath would read as a failure.
  const queue = useJobs(load);

  return (
    <main className="tw:mx-auto tw:max-w-4xl tw:px-6 tw:py-10 tw:font-sans">
      <header className="tw:mb-8">
        <h1 className="tw:font-serif tw:text-3xl tw:text-foreground">Spideryarn</h1>
        <p className="tw:mt-1 tw:text-sm tw:text-muted-foreground">
          Read deeply, at whatever level of detail you need. Pick a piece.
        </p>
      </header>

      <AddArticle queue={queue} />

      {error && (
        <p className="tw:rounded-md tw:border tw:border-destructive/40 tw:bg-destructive/10 tw:p-4 tw:text-sm tw:text-foreground">
          {error}
        </p>
      )}
      {!error && articles === null && (
        <p className="tw:text-sm tw:text-muted-foreground">Loading…</p>
      )}
      {articles?.length === 0 && (
        <p className="tw:text-sm tw:text-muted-foreground">
          Nothing on the shelf yet. Paste a URL above and it'll be here in a minute or two.
        </p>
      )}

      <ul className="tw:m-0 tw:flex tw:list-none tw:flex-col tw:gap-3 tw:p-0">
        {articles?.map((a) => (
          <li key={a.slug}>
            <Card entry={a} />
          </li>
        ))}
      </ul>
    </main>
  );
}

/** `12 Aug 2026`. Absent or unparseable dates simply don't show. */
function whenAdded(iso: string): string {
  const t = Date.parse(iso);
  return Number.isNaN(t)
    ? ""
    : new Date(t).toLocaleDateString(undefined, {
        day: "numeric",
        month: "short",
        year: "numeric",
      });
}

function Card({ entry }: { entry: LibraryEntry }) {
  // Only the facts this article actually has. A filtered join beats a chain of
  // `&&`s that can leave a stranded separator — same reasoning as Masthead.
  const facts = [
    entry.byline,
    entry.siteName,
    `~${entry.minutes} min`,
    `${entry.blocks} blocks`,
  ].filter(Boolean) as string[];

  return (
    <Link
      href={readHref(entry.slug)}
      className="tw:block tw:rounded-lg tw:border tw:border-border tw:bg-card tw:p-5 tw:no-underline tw:transition-colors tw:hover:border-highlight/60 tw:focus-visible:border-highlight tw:focus-visible:outline-none"
    >
      <h2 className="tw:m-0 tw:font-serif tw:text-xl tw:leading-snug tw:text-foreground">
        {entry.title}
      </h2>

      <p className="tw:mt-1.5 tw:mb-0 tw:flex tw:flex-wrap tw:items-center tw:gap-x-2 tw:gap-y-1 tw:text-xs tw:text-muted-foreground">
        {facts.map((f, i) => (
          <span key={f}>
            {i > 0 && <span className="tw:mr-2 tw:opacity-50">·</span>}
            {f}
          </span>
        ))}
        {entry.fixture && (
          <span
            className="tw:rounded tw:border tw:border-border tw:px-1.5 tw:py-0.5"
            title="The committed placeholder fixture, not real pipeline output — see example/README.md"
          >
            fixture
          </span>
        )}
      </p>

      {/* The whole piece in one sentence. Serif, because it is the article
          talking rather than the app — the same distinction the reading view
          makes between prose and chrome. */}
      {entry.gist && (
        <p className="tw:mt-3 tw:mb-0 tw:font-serif tw:text-[0.95rem] tw:leading-relaxed tw:text-ink-faint">
          {entry.gist}
        </p>
      )}

      <p className="tw:mt-3 tw:mb-0 tw:flex tw:items-center tw:gap-4 tw:text-xs tw:text-muted-foreground">
        <span className="tw:inline-flex tw:items-center tw:gap-1.5">
          <FileText size={13} />
          {entry.words.toLocaleString()} words
        </span>
        {entry.comments > 0 && (
          <span
            className="tw:inline-flex tw:items-center tw:gap-1.5 tw:text-highlight"
            title={`${entry.comments} question${entry.comments === 1 ? "" : "s"} asked about this article`}
          >
            <MessageCircle size={13} />
            {entry.comments}
          </span>
        )}
        <span className="tw:ml-auto">{whenAdded(entry.addedAt)}</span>
      </p>
    </Link>
  );
}
