/**
 * The homepage: the shelf of articles, and everything above it — the search
 * box, the sort chips, the view toggle, the box for adding one.
 *
 * Greg, 2026-08-25:
 *
 * > have a homepage that enables us to browse past documents, and then if I
 * > click on one of the documents, it takes us to this interface that we've been
 * > building using a slug of the URL
 *
 * A card is a *decision aid*, not a summary — you are choosing what to read, and
 * the thing that decides it is what the piece says and how long it will take.
 * So the blurb is the tree root's gist: one sentence about the whole article,
 * generated by the same pass that fills the L0 column. That is the product's own
 * idea turned on its own library, and it costs nothing because the sentence
 * already exists. See docs/project/library.md.
 *
 * ## What this file is now, and what it is not
 *
 * It is **the page**: the fetch, the URL state, and the four narrowings that
 * turn a list of articles into the list on screen. It is deliberately not the
 * things it draws. Since 2026-08-26 the shelf has two renderers rather than
 * one, and everything they share had to stop living inside one of them:
 *
 * | File | What |
 * |---|---|
 * | lib/DataTable.tsx | **reusable**: the chips, the dense table, the TanStack options that are decisions |
 * | lib/table-sort.ts | **reusable**: sorting state ⇄ URL, the collator, `sinkLast` |
 * | library-columns.tsx | what the shelf can be sorted by, and how each column draws |
 * | ShelfControls.tsx | the shelf's own filtering, column-visibility and view controls |
 * | ShelfEntry.tsx | the card, the five buttons, rename-in-place, the tooltip |
 *
 * **One sort state, two renderers**, which is the shape Greg asked for when he
 * said he liked the cards and wanted them sortable anyway. The order, the
 * filter and the search are all resolved here, above the branch, so the two
 * views cannot disagree about what is on the shelf.
 *
 * Styled with Tailwind utilities rather than a block in styles.css, and that is
 * the rule rather than a preference: this page is chrome, and chrome is what
 * shadcn and Tailwind were adopted for
 * (docs/project/web-client.md#tailwind-and-shadcn-components). The reading view
 * stays hand-written, because its geometry is not something utilities can say.
 * Note the `tw:` prefix on every class — unprefixed names do nothing here.
 *
 * See docs/plans/260826k-library-shelf-actions-and-search.md and
 * docs/plans/260826y-library-sorting.md.
 */
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { throttle, useQueryState } from "nuqs";
import type { OnChangeFn, SortingState } from "@tanstack/react-table";
import { functionalUpdate } from "@tanstack/react-table";
import { Search, Shield, Undo2, User, X } from "lucide-react";
import { isAdmin } from "../admin.js";
import type { LibraryEntry, LibraryHit } from "../types.js";
import { AddArticle } from "./AddArticle.js";
import { isImeComposing } from "./key-chord.js";
import { ADDED_NOTE, CARD_NOTES, CHIP_ORDER, DEFAULT_BY, libraryColumns } from "./library-columns.js";
/* The shelf's own Feedback control, in the masthead row below — the same
   trigger the corner and the dock draw, in a third shape. FeedbackButton.tsx §
   `FEEDBACK_SHAPE.masthead`. */
import { FeedbackTrigger } from "./FeedbackButton.js";
import { BatchPanel } from "./BatchPanel.js";
import { ReadThisButton } from "./ReadThis.js";
import { FreeAllowance } from "./FreeAllowance.js";
import { DataTable, naturalDirections, useSortedTable } from "./lib/DataTable.js";
import { capRows } from "./lib/row-cap.js";
import { isAllNatural, sinkLast, sortingFromUrl, sortingToUrl } from "./lib/table-sort.js";
import { Link } from "./Link.js";
import { LogoLetters, LogoMark } from "./LogoGlyphs.js";
import { useLogoAnimation } from "./logo-animation.js";
import { foldWithMap, libraryHitHref, queryTerms } from "./library-hits.js";
import {
  libraryArchivedParam,
  libraryPublicParam,
  libraryByParam,
  libraryQueryParam,
  libraryShowParam,
  libraryTagsParam,
  libraryTopicsParam,
  libraryViewParam,
  sortDirParam,
} from "./params.js";
import { chosenTopics, isArchived, narrowShelf, tagFacets, topicCountsForVisible, topicMembers } from "./shelf-narrow.js";
import { ArticleTopicsContext, ShelfRowTopics, TopicsExpectedContext } from "./ShelfRowTopics.js";
import { mightHaveTopics, ShelfTerms, ShelfTermsLoading } from "./ShelfTerms.js";
import { ShelfTagFilter } from "./ShelfTagFilter.js";
import { articleTopics } from "./article-topics.js";
import { shelfKeyOf, topicsExpected, useShelfTopics } from "./useShelfTerms.js";
import { pageTitle, useDocumentTitle } from "./page-title.js";
import { ADMIN_HREF, PROFILE_HREF } from "./router.js";
import { media } from "./media.js";
import { ArchivedMark, ShelfCard } from "./ShelfEntry.js";
import { ShelfControls, type ShelfFilter } from "./ShelfControls.js";
import { ShelfPhoneHint } from "./ShelfPhoneHint.js";
import { ShelfPublicSection } from "./ShelfPublicSection.js";
import { useShelfHiddenColumns } from "./shelf-hidden-columns.js";
import { SiteFooter } from "./SiteFooter.js";
import { Tooltip, TooltipGroup } from "./Tooltip.js";
import { useJobs } from "./useJobs.js";
import { MIN_QUERY, useLibrarySearch } from "./useLibrarySearch.js";
import { usePublicShelf } from "./PublicLibraryPage.js";
import { type ArchivedTally, ShelfSearchAlso } from "./ShelfSearchAlso.js";
import { useNow } from "./useNow.js";
import { useSession } from "./useSession.js";
import { useShelf } from "./useShelf.js";
import { usePreloadRecent } from "./usePreloadRecent.js";
import { useSlow } from "./useSlow.js";
import { useRenderCount } from "./perf.js";
import { layoutViewportWidth } from "./reader/measure.js";
import { articleTitleVoice, voiceClass, withVoice } from "./voice.js";

export function Library({
  readerId,
}: {
  /**
   * Whose shelf this is, from `SignedIn` in App.tsx.
   *
   * A prop rather than `user?.id` off the `useSession()` below, even though the
   * two are the same string: `useShelf` reads this reader's saved copy out of
   * IndexedDB before the live answer lands, and *which reader* is then a fact
   * the shelf depends on rather than a detail of the chrome. `SignedIn` has a
   * non-optional `User`, so passing it down makes the id non-optional here —
   * the `?.` that `useSession` forces on every other caller cannot creep into
   * the one place it would mean "look in nobody's cache".
   * docs/plans/260903g-faster-shelf-load-and-tidier-homepage-controls.md § Stage 5.
   */
  readerId: string;
}) {
  useRenderCount("Library");
  /* Who the Admin link is drawn for, and whose address the Profile tooltip
     names. `useSession` is already subscribed once at the top of the app
     (App.tsx), and a second subscription is one listener rather than a second
     source of truth — the SDK is the source, and both read it. */
  const { user } = useSession();
  const shelf = useShelf(readerId);
  const { articles, error, reload } = shelf;
  /* The five opened most recently, fetched now so that reopening one does not
     wait on the server — report spya-j78fff, usePreloadRecent.ts. */
  usePreloadRecent(articles);
  const slow = useSlow(articles === null);

  /* Every one of these is in the URL rather than in `useState`, which is the
     rule the whole app runs on (docs/project/url-state.md): reload the
     homepage, or send somebody the link, and you get the same shelf back.
     Until 2026-08-26 the search box was `useState` and the order was whatever
     the server happened to send, so neither survived a reload. */
  const [rawQuery, setQuery] = useQueryState("q", libraryQueryParam);
  const [by, setBy] = useQueryState("by", libraryByParam);
  const [rawDir, setDir] = useQueryState("dir", sortDirParam);
  const [view, setView] = useQueryState("view", libraryViewParam);
  const [show, setShow] = useQueryState("show", libraryShowParam);
  /* The topics row and the archive switch — docs/project/shelf-terms.md. */
  const [requestedTopics, setTopics] = useQueryState("topics", libraryTopicsParam);
  /* The reader's own tags, in their own row and their own key — plan 261003d. */
  const [requestedTags, setTags] = useQueryState("tags", libraryTagsParam);
  const [archivedOn, setArchivedOn] = useQueryState("archived", libraryArchivedParam);
  /* Include public — what other readers have shared, in its own section under
     the list. ShelfPublicSection.tsx; plan 261002b § Part A. */
  const [publicOn, setPublicOn] = useQueryState("public", libraryPublicParam);

  /**
   * Whether the shelf is showing every row or only the first `SHELF_ROW_CAP`.
   *
   * **One flag for both views, not one each.** The two views are the same list
   * painted twice (url-state.md), so if the list is "all of them" in one
   * painting it is all of them in the other; a per-view flag would quietly make
   * the view switch a filter as well. There is no "show fewer", so the only
   * thing two flags would buy is pressing the button a second time.
   *
   * **Deliberately not in the URL**, unlike every other bit of state on this
   * page. The rule in docs/project/url-state.md is that the query string says
   * *how you are looking at* the shelf, and this is nearer to a scroll position
   * than to a view: nobody wants to send somebody a link to the first fifty.
   *
   * **And deliberately here rather than inside `DataTable`.** As component-local
   * state it would reset every time that component unmounted — which is on every
   * switch to cards and every search that matches nothing — so "show all" would
   * have quietly undone itself in exactly the places a reader would notice.
   * GPT Sol, 2026-09-06.
   *
   * It does *not* reset when the search changes, which is the other half of the
   * same choice: "show me all of them" reads as a standing preference, not as an
   * answer to one query.
   */
  const [expanded, setExpanded] = useState(false);

  const query = rawQuery ?? "";

  /* The tab. Bare, this is the homepage and so the one page that leads with the
     app's own name; narrow the shelf and what you narrowed it to takes the
     front instead. See src/web/page-title.ts. */
  useDocumentTitle(pageTitle({ kind: "library", query, unread: show === "unread" }));

  /**
   * Make a `push` change to the view, taking any half-typed search with it.
   *
   * `?q=` is written on a 200ms debounce, so a click landing inside that window
   * pushes a history entry that does not have the query in it yet — and the
   * query then *replaces* itself into the new entry a moment later. Back then
   * undoes the sort **and** the search together, having appeared to record only
   * the sort. Writing `q` here with the limit lifted puts it in the same batch
   * as the push, so one entry carries both. nuqs queues every synchronous write
   * until the next tick and flushes them as one URL update, which is also why
   * `setBy` and `setDir` are one history entry rather than two.
   *
   * Caught by a cross-family review, 2026-08-26.
   */
  const pushView = useCallback(
    (write: () => void) => {
      write();
      void setQuery(query || null, { limitUrlUpdates: throttle(0) });
    },
    [query, setQuery],
  );

  /* One clock reading, re-read once a minute and handed to everything that
     prints a relative date — see useNow.ts for both halves of why. */
  const now = useNow();

  /* `ShelfRowTopics` is one stable component, reading its topics from context,
     so the topics answer landing does not rebuild these (plan 261005a). */
  const columns = useMemo(
    () => libraryColumns(shelf, now, archivedOn, ShelfRowTopics),
    [shelf, now, archivedOn],
  );
  const natural = useMemo(() => naturalDirections(columns), [columns]);
  /* `DEFAULT_BY` as the fallback: a URL naming nothing we recognise lands on
     the ordinary shelf rather than on an unsorted list with no chip pressed.

     **`rawDir` straight in, `null` and all.** No `dir` in the URL means "each
     key goes whichever way it naturally goes", which is a different answer per
     column, so `sortingFromUrl` fills the gaps rather than nuqs supplying a
     default (params.ts § sortDirParam has the hour that rule cost). This line
     used to read `rawDir ?? []` above the memo — a fresh array every render,
     which made this memo re-run every render, which made TanStack recompute and
     queue a page-index reset, which set state and rendered again, for ever:
     docs/postmortems/260827e-shelf-render-loop.md. */
  const sorting = useMemo(
    () => sortingFromUrl(by, rawDir, natural, DEFAULT_BY),
    [by, rawDir, natural],
  );

  /* The topics: which exist (from the server, over active — or active and
     archived with `?archived=1`), and which of the ones in the URL apply. A
     key applies only once topics have loaded, and one missing from a settled
     answer is dropped from the URL with `replace` — useShelfTerms.ts. */
  const dropTopics = useCallback(
    (kept: string[]) => void setTopics(kept.length ? kept : null, { history: "replace" }),
    [setTopics],
  );
  const shelfTopics = useShelfTopics({
    articles,
    archivedList: shelf.archived,
    archivedOn,
    requested: requestedTopics,
    drop: dropTopics,
  });
  const { terms, inArchive, topics, members } = shelfTopics;
  /* Each topic's hue and each article's topics, once per answer, for the
     Topics row and for the pills on every card and table row
     (article-topics.ts). */
  const topicsOfArticles = useMemo(() => articleTopics(terms.data?.terms ?? []), [terms.data?.terms]);

  /* **The scope: one list.** The active shelf, and — with the Archived chip on
     and the archive loaded — the archived articles in the same array, each
     carrying its own `archivedAt` (plan 260929a, Greg's report 4V; Sol R4).
     Combined here, **before** TanStack sorts, so the sort, the fixture sink
     and the row cap below apply to both halves as one list; a second list at
     the foot of the shelf could be neither sorted with the first nor capped
     with it. While the archive is loading, or has failed, this is the active
     shelf plus any archive mutations whose server answers we already hold —
     never `null` because of the archive (Sol R3). */
  const scope = useMemo(
    () => shelfScope(articles, shelf.archivedVisible, archivedOn),
    [articles, archivedOn, shelf.archivedVisible],
  );

  /* Every slug that is yours, so Include public does not list your own shared
     articles a second time without your verbs on them. Include archive edits
     even before the archive is loaded: the shared public snapshot can still
     contain an article you have just archived. */
  const ownSlugs = useMemo(
    () => new Set([...(articles ?? []), ...shelf.archivedVisible].map((a) => a.slug)),
    [articles, shelf.archivedVisible],
  );

  /* The archive is fetched when the chip is on and the list is missing — on a
     press, on a direct `?archived=1` visit, and after anything sets the list
     back to `null` (a change of reader). An effect rather than a call in the
     chip's handler for the second and third. Keyed on exactly those, so a
     failure is not retried in a loop: `archived` stays `null` and nothing
     here changes until the chip is turned off and on again. */
  const { archived: archivedList, loadArchived } = shelf;
  useEffect(() => {
    if (archivedOn && archivedList === null) void loadArchived();
  }, [archivedOn, archivedList, loadArchived]);

  /* Matcher one: the shelf itself, filtered in the browser, then narrowed by
     the Unread chip, then by every chosen topic — one function, in one order,
     over the one list (shelf-narrow.ts). The *order* is no longer ours —
     TanStack owns it below — but which rows exist still is.

     `useMemo` because this runs on every keystroke over every article, and
     because the identity of the array it returns is what decides whether the
     whole table is rebuilt. */
  /* **The reader's own tags as facets**, from the entries in scope (each
     carries its tags), so they need no request and are never "loading". A
     chosen tag no entry in scope carries is ignored, never dropped from the
     URL: an edit in flight or a list still loading must not eat a filter
     (plan 261003d, Sol 3). Keyed on the joined string, for the render-loop
     reason `useChosenTopics` gives. */
  const tagList = useMemo(() => tagFacets(scope ?? []), [scope]);
  const askedTags = requestedTags.join(",");
  const tagsChosen = useMemo(
    () => chosenTopics(askedTags ? askedTags.split(",") : [], scope ? tagList : null),
    [askedTags, scope, tagList],
  );
  /* Both rows' chosen sets, one AND (shelf-narrow.ts § `withTopics`). */
  const chosenSets = useMemo(
    () => [...members, ...topicMembers(tagList, tagsChosen)],
    [members, tagList, tagsChosen],
  );
  const rows = useMemo(
    () => (scope ? narrowShelf(scope, { query, unread: show === "unread", topics: chosenSets }) : null),
    [scope, query, show, chosenSets],
  );
  /* The expensive search has already run in the row memo. Count from its
     result instead of repeating it over every article on each keypress. */
  const counts = useMemo(
    () =>
      topicCountsForVisible(
        (rows ?? []).map((entry) => entry.slug),
        terms.data?.terms ?? [],
      ),
    [rows, terms.data?.terms],
  );
  const tagCounts = useMemo(
    () => topicCountsForVisible((rows ?? []).map((entry) => entry.slug), tagList),
    [rows, tagList],
  );
  const toggleTag = useCallback(
    (key: string) =>
      pushView(() => {
        const was = requestedTags;
        const next = was.includes(key) ? was.filter((k) => k !== key) : [...was, key];
        void setTags(next.length ? next : null);
      }),
    [pushView, requestedTags, setTags],
  );

  /* Toggled against what the URL asks for rather than what applies, so a key
     the server has not reached yet (`pending > 0`) is not lost by pressing a
     different chip. */
  const toggleTopic = useCallback(
    (key: string) =>
      pushView(() => {
        const was = requestedTopics;
        const next = was.includes(key) ? was.filter((k) => k !== key) : [...was, key];
        void setTopics(next.length ? next : null);
      }),
    [pushView, requestedTopics, setTopics],
  );

  /**
   * The sorting state, written straight back to the address bar.
   *
   * TanStack hands us an updater rather than a value — it computes what a click
   * means, including which end a new column starts at and whether shift was
   * held — so this applies it to the current state and serialises the result.
   * That is the whole of what replaced a hand-written `nextSort`.
   */
  const onSortingChange = useCallback<OnChangeFn<SortingState>>(
    (updater) => {
      /* Applied to `sorting` — the very array TanStack was handed as its state,
         so what it computed the update against and what we apply it to cannot
         be two different things. */
      const next = functionalUpdate(updater, sorting);
      /* Never empty. `enableSortingRemoval: false` should make that impossible,
         but an empty sort would fall back to whatever order the data arrived
         in — a state the reader cannot name or ask for — so it is refused here
         as well as configured against. */
      if (next.length === 0) return;
      const url = sortingToUrl(next);
      pushView(() => {
        void setBy(url.by);
        /* Left out when it says nothing the columns would not have said
           themselves, which keeps `?by=title` short — and correct, since an
           absent `dir` is what makes the per-column fallback run at all. */
        void setDir(isAllNatural(next, natural) ? null : url.dir);
      });
    },
    [sorting, natural, pushView, setBy, setDir],
  );

  /* The columns the reader has hidden in table view, remembered in this
     browser — shelf-hidden-columns.ts; plan 260928a, Decision 3. */
  const [columnVisibility, onColumnVisibilityChange] = useShelfHiddenColumns(columns);

  const table = useSortedTable({
    data: rows ?? EMPTY,
    columns,
    sorting,
    onSortingChange,
    rowId: slugOf,
    columnVisibility,
    onColumnVisibilityChange,
  });

  /* The fixture last, in every order and both directions. It is a committed
     placeholder rather than something the reader added, and the server has
     always kept it at the foot of the shelf — sorting in the browser without
     carrying that over puts a demo excerpt above the reader's own library the
     first time anybody sorts by length. */
  const modelRows = table.getRowModel().rows;
  const primary = sorting[0]?.id;
  const sorted = useMemo(() => {
    /* Two sinks, in this order.

       **Missing values last, whichever way the arrow points.** `sortUndefined`
       is the option for this and it is switched off, because TanStack gets it
       wrong when two values are both missing — see lib/table-sort.ts §
       numberOrMissing. So the columns sort missing *low*, consistently, and the
       rows whose primary key is missing are moved down here. Ascending by "last
       opened" must not fill the top of the shelf with everything you have never
       opened: that is a useful thing to want, and it is what the Unread chip is
       for.

       **Then the fixture**, below even those. It is a committed placeholder
       rather than something the reader added, and the server has always kept it
       at the foot of the shelf. */
    const missingLast = primary
      ? sinkLast(modelRows, (r) => r.getValue(primary) === undefined)
      : modelRows;
    return sinkLast(missingLast, (r) => !!r.original.fixture);
  }, [modelRows, primary]);

  // Reload the shelf the moment a job finishes, rather than telling the reader
  // to reload the page — they just watched the five steps go green, and an
  // empty shelf underneath would read as a failure.
  const queue = useJobs("watches-queue", reload);

  // Matcher two: the passages inside the articles, from the server.
  /* Counts and passages belong to this shelf snapshot too. Archiving,
     restoring, or publishing a revision changes the answer at the same query.
     Use the existing shelf identity; opens and other reading state leave it
     unchanged. Include known archive edits even with the chip off. */
  const searchShelfKey = useMemo(
    () => `${readerId}:${shelfKeyOf(articles, shelf.archivedVisible, true) ?? ""}`,
    [readerId, articles, shelf.archivedVisible],
  );
  const passages = useLibrarySearch(query, archivedOn, searchShelfKey);

  /* **One read of the public listing**, for the Include public section and for
     the count beside the search's answer, so the two are the same snapshot
     (plan 261002b § Part D). Started only once the live owner shelf is in —
     a saved copy cannot say which public articles are somebody else's — and
     only when something wants it. */
  const publicListing = usePublicShelf(
    shelf.liveArticlesLoaded && (publicOn || queryTerms(query).length > 0),
  );

  /* The archive's half of that count: the server's, off the passage search
     run without the archive — taken only from the answer to *this* query, and
     only once the query is long enough to have been searched at all. */
  const archivedTally: ArchivedTally = useMemo(() => {
    const eligible = query.trim().length >= MIN_QUERY;
    const current =
      passages.asked && passages.resultsQuery === query.trim() && !passages.resultsArchived;
    return {
      count: eligible && current ? (passages.archivedArticles ?? null) : null,
      checking: eligible && passages.searching,
    };
  }, [query, passages]);

  const searching = query.trim().length > 0;
  /* Every count is over the one list: `total` is what is in scope, `showing`
     what survives the narrowing. The archived share of each is named in the
     "n of m" line when the archive is in scope. */
  const total = scope?.length ?? 0;
  /* Whether each card and row holds a line for its topic pills, so the pills
     landing does not move the shelf (plan 261005h § C). Over `total`, the
     count the placeholder Topics row is given below. */
  const expectTopics = topicsExpected(terms, mightHaveTopics(total));
  const showing = rows?.length ?? 0;
  const archivedShowing = useMemo(() => (rows ?? []).filter(isArchived).length, [rows]);
  // Said only when something is actually being hidden. "12 of 12" is noise.
  const narrowed =
    (searching || show === "unread" || topics.length > 0 || tagsChosen.length > 0) && showing !== total;

  /* The slugs the Unread chip lets through, whatever the search box says — the
     passages are the answer to the search, so narrowing them by the search
     twice would be wrong. `null` when the chip is off, which is "do not narrow"
     rather than "narrow to nothing". */
  /* Over `scope`, not the active shelf alone: with Include archived on, an
     archived article nobody has opened is as unread as any other, and its
     passages must not vanish when the cards keep it (plan 260930d). */
  const unread = useMemo(
    () =>
      show === "unread" && scope
        ? new Set(scope.filter((a) => a.opens === 0).map((a) => a.slug))
        : null,
    [scope, show],
  );

  /* Whichever column is sorted first decides what a card says about itself. */
  const note = CARD_NOTES[sorting[0]?.id ?? ""] ?? ADDED_NOTE;

  /* What this view draws, and whether there is a "show all" to offer. Taken
     from `sorted`, which is after both `sinkLast` passes — capping before the
     sort would pick its fifty out of the wrong order. lib/row-cap.ts. */
  const capped = capRows(sorted, SHELF_ROW_CAP[view], expanded);

  /* **`+ var(--safe-top)`, since 2026-09-08, and it is a precondition rather
     than a tidy-up.** `index.html` carries `viewport-fit=cover`, so on an
     installed phone the document is laid out across the whole physical screen
     and every page has to add back the edge it faces (styles/tokens.css). Every
     other signed-in `<main>` does — `ProfilePage`, `PrivacyPage`, `ContactPage`
     and `ChangelogPage` at `3.5rem + --safe-top`, `Metadata` and `Tweets` at
     `2.5rem + --safe-top` — and this page's bare `pt-10` was the one that did
     not, so on an iPhone the shelf's own `<h1>` sat at y=40 inside a 59px
     inset: under the clock. Measured 2026-09-08 with the insets stood up in
     Chrome, because they are `0px` on every machine we develop on and no
     screenshot from this box shows it.

     It matters *here* because the Feedback button moved into the header row
     below. `.fb-button` was `top: var(--safe-top)` and cleared the notch on its
     own; a control in that row inherits whatever this `<main>` says, so moving
     it without this line would have put it under the status bar on the very
     device Greg filed the report from.

     **The number is still this page's own** — 2.5rem, exactly what `pt-10` was
     — because HomeLogo.tsx § Why the corner is free records that a page's top
     clearance is its own business and there is no shared constant. This adds
     the inset and changes nothing on a desktop, where `env(safe-area-inset-top)`
     is `0px`. */
  return (
    <main className="tw:mx-auto tw:max-w-4xl tw:px-6 tw:pt-[calc(2.5rem_+_var(--safe-top))] tw:font-sans">
      <header className="tw:mb-8">
        {/* The masthead links are deliberately the quietest thing on the page —
            the faint-until-hovered treatment `BackLink` has (BackLink.tsx), so
            the two read as one convention. This paragraph used to argue that
            the design reference in particular should not be stepped over by a
            reader arriving at their shelf; it is on /admin since 2026-09-05,
            which is that argument taken to its conclusion. */}
        {/* Wraps rather than letting the links crush the wordmark in a narrow
            window. They keep `justify-between` when they fit and drop to their
            own line when they do not — and `gap-y-1` keeps that second line off
            the strapline below. */}
        <div className="tw:flex tw:flex-wrap tw:items-baseline tw:justify-between tw:gap-x-4 tw:gap-y-1">
          {/* The spider beside the name, which every other page has had since
              2026-08-26 and this one — the page the app opens on — did not.
              Greg, 2026-09-08: *"can you include the logo itself in the
              top-left of the logged-in Homepage next to the wordmark"*.

              **Deliberately not `HomeLogo`**: this is home, so there is
              nothing to link to (App.tsx says why). **Spider and heading
              animate as one wordmark** since 2026-09-30 — § ShelfWordmark
              below.

              `items-center` in its own row so the glyph centres on the word
              while the header's outer flex keeps its baseline alignment for the
              links opposite. */}
          <ShelfWordmark />
          {/* One group, so that once the first card is up its neighbour opens
              instantly as the pointer runs along the row — Tooltip.tsx. The
              delays are the ones the dock and the metadata cards use, because
              this is the same kind of thing: a short row of quiet chrome whose
              labels are already visible, where the tooltip adds a sentence
              rather than naming the button. */}
          <TooltipGroup delay={{ open: 300, close: 120 }} timeoutMs={400}>
            {/* **`ml-auto`, so this group is right-aligned on its own line
                too.** The row above is `flex-wrap` + `justify-between`, and
                `space-between` puts a *single* item on a line at that line's
                start — so as soon as this group wrapped, which is every phone,
                it sat hard against the left margin with the width of the page
                empty to its right.

                That was invisible while the group was only `Profile` and
                `Admin`, and stopped being invisible on 2026-09-08 when the
                Feedback trigger joined it: Greg's report asks for that button
                in the **top right**, and on the phone he filed it from the
                answer was the top left. GPT Sol caught it in review; measured
                at 390px, the group ran 24→250 in a 366px column.

                `ml-auto` and not `justify-end` on the parent, which would push
                the wordmark about on the unwrapped line. On that line this
                changes nothing — `justify-between` had already put the free
                space here — so it costs one class and only acts once the row
                has wrapped. */}
            <div className="tw:ml-auto tw:flex tw:items-baseline tw:gap-4">
              {/* Home is where a global thing gets a way in. The profile page
                  holds what is true of the reader on every article, so a link to
                  it from inside one article would be a link nobody finds —
                  docs/project/reader-profile.md. It used to be ordered before
                  Design on the grounds that this one is for the reader and that
                  one was developer furniture; Design left for /admin on
                  2026-09-05, which settled the argument. */}
              <Tooltip
                placement="bottom"
                keepSide
                content={
                  <Tip>
                    What the model knows about who it is writing for.
                    {/* The address is the answer to "am I signed in as the
                        right person", which is the question this link gets
                        asked most. Second, under what the page is for, and
                        simply absent until the session arrives — a card saying
                        "Signed in as undefined" is worse than one that does not
                        mention it. */}
                    {user?.email && (
                      <span className="tw:mt-1 tw:block tw:text-ink-faint">
                        {/* `break-all` on the address alone: `.tooltip` caps at
                            22rem and sets no `overflow-wrap`, so a long address
                            with nothing to break on would run out of the panel
                            rather than wrap. GPT Sol, 2026-08-28. */}
                        Signed in as <span className="tw:break-all">{user.email}</span>
                      </span>
                    )}
                  </Tip>
                }
              >
                <Link
                  href={PROFILE_HREF}
                  className="tw:inline-flex tw:items-center tw:gap-1.5 tw:text-xs tw:text-ink-faint tw:no-underline tw:pointer-coarse:min-h-10 tw:hover:text-highlight-text"
                >
                  <User size={13} />
                  Profile
                </Link>
              </Tooltip>
              {/* **Only the administrator sees this, and only the server enforces
                  it.** Drawing or not drawing a link is a courtesy — the page is
                  in the bundle either way, and typing the address gets a
                  non-administrator the shelf back (App.tsx). src/admin.ts. */}
              {isAdmin(user?.id) && (
                <Tooltip
                  placement="bottom"
                  keepSide
                  content={<Tip>Who has signed up, and how much they have read.</Tip>}
                >
                  <Link
                    href={ADMIN_HREF}
                    className="tw:inline-flex tw:items-center tw:gap-1.5 tw:text-xs tw:text-ink-faint tw:no-underline tw:pointer-coarse:min-h-10 tw:hover:text-highlight-text"
                  >
                    <Shield size={13} />
                    Admin
                  </Link>
                </Tooltip>
              )}
              {/* **Design is not here any more**, since 2026-09-05:
                  > Move the Design link on the logged-in Homepage into /admin
                  > — Greg, 2026-09-05 (SPIDERYARN-READING2-1T)

                  It is an `Entry` on the /admin index now (AdminPage.tsx). The
                  masthead is for things a reader does — their profile, their
                  shelf — and a page of colour tokens is developer furniture that
                  every signed-in reader was being shown. Note that moving the
                  *link* gates nothing: `/design` is still open to anybody signed
                  in, deliberately, for the reason admin.md gives about the Admin
                  link beside this one. */}
              {/* **Feedback, last in the row and therefore right-most**, since
                  2026-09-08:
                  > Show the Feedback button in the top right of the logged in
                  > Homepage
                  > — Greg, 2026-09-07 (SPIDERYARN-READING2-2C)

                  **It was already in the top right, and that is the point.**
                  The corner trigger drew on this page at every width with
                  nothing painted over it — but as a bare `--ink-faint` glyph
                  fixed to the *window*, a hand's width from this cluster of
                  identically-styled controls, and with its label given up
                  entirely below 731px. Two top-rights, and this is the one a
                  reader looks at. App.tsx stops drawing the corner one here.

                  Last rather than first because this row is right-aligned, so
                  last is nearest the corner the button used to occupy and the
                  place Greg's report points at. Ahead of nothing else: `Admin`
                  is only drawn for the administrator, so for an ordinary reader
                  the row reads `Profile · Feedback`.

                  Inside the `TooltipGroup` above, so its card opens instantly
                  once a neighbour's has — it is the same kind of chrome and
                  should not feel like a different one. The shape it wears is
                  `FEEDBACK_SHAPE.masthead` in FeedbackButton.tsx, which is
                  where the classes and the reasoning live; nothing about a
                  report changes, since `FeedbackHost` has always sent
                  `slug: null` from every page that is not an article. */}
              <FeedbackTrigger variant="masthead" />
            </div>
          </TooltipGroup>
        </div>
        {/* **No tagline, since 2026-09-29.** It read "Read deeply, at whatever
            level of detail you need. Pick a piece." Greg, SPIDERYARN-READING2-4W:
            *"Or maybe actually just remove the tagline from the logged-in
            Homepage."* The reader here has already signed up for the pitch.
            If it ever comes back, his wording was "Read deeply & efficiently".
            docs/plans/260929a-logo-beside-the-wordmark-beta-to-the-right-no-shelf-tagline.md. */}
      </header>

      {/* **On a phone, until dismissed: a bigger screen is better.** Greg,
          spya-fcbnhq. Above the add box so it is the first thing read, and in
          flow so it scrolls away. ShelfPhoneHint.tsx; plan 261002b § Part C. */}
      <ShelfPhoneHint />

      <AddArticle queue={queue} />

      {/* **Several files dropped at once**, each added with only its title,
          authors and abstract read — nothing at all while there is no batch.
          BatchPanel.tsx; plan 261001m. */}
      <BatchPanel />

      {/* **The free allowance**, for Free and lapsed readers only — what is
          used, what is left, and a collapsed *How free articles work*. Below
          the add box because that is the act it counts. FreeAllowance.tsx;
          plan 261001m. */}
      <FreeAllowance />

      {error && (
        <p className="tw:rounded-md tw:border tw:border-destructive/40 tw:bg-destructive/10 tw:p-4 tw:text-sm tw:text-foreground">
          {error}
        </p>
      )}
      {shelf.actionError && (
        <p className="tw:mb-3 tw:rounded-md tw:border tw:border-destructive/40 tw:bg-destructive/10 tw:px-4 tw:py-2 tw:text-sm tw:text-foreground">
          {shelf.actionError}
        </p>
      )}

      {shelf.undoable && (
        <UndoStrip title={shelf.undoable.title} onUndo={() => void shelf.undo()} />
      )}

      {/* **Directly above the list it filters**, and below the box for adding
          one, since 2026-09-03:

          > Move the search bar so it's just above the list of articles.
          >
          > — Greg, 2026-09-03

          It used to be the first thing under the header — so the box you use to
          *find* an article sat above the box you use to *add* one, with
          everything else between it and the list it narrows.

          `trim()` rather than `v || null`: spaces alone serialise to `?q=%20`,
          which the parser reads back as `null`. So the box emptied itself on
          reload while the URL still carried something — the one thing this
          page's URL state is supposed to make impossible. A value that merely
          *ends* in a space is kept as typed. */}
      <SearchBox value={query} onChange={(v) => void setQuery(v.trim() ? v : null)} />

      {/* The controls sit directly above the list they govern, and only once
          the shelf has answered. A sort control over an empty shelf is
          furniture, so with nothing in scope only the Archived chip is drawn
          (`bare`) — it has to be, or a reader whose every article is archived
          could not reach them (plan 260929a, Sol R2). */}
      {articles !== null && (
        <ShelfControls
          table={table}
          chipOrder={CHIP_ORDER}
          view={view}
          onView={(v) => pushView(() => void setView(v))}
          filter={show}
          onFilter={(f) => pushView(() => void setShow(f))}
          archived={archivedOn}
          onArchived={(on) => pushView(() => void setArchivedOn(on ? true : null))}
          publicOn={publicOn}
          onPublic={(on) => pushView(() => void setPublicOn(on ? true : null))}
          bare={total === 0}
        />
      )}

      {/* The archive's own state, while the chip is on and there is no list
          yet to merge. The active rows stay painted underneath either way
          (Sol R3). "Nothing archived" too, or an on chip that changed nothing
          would look like a chip that did nothing. */}
      {archivedOn && articles !== null && (
        <ArchiveStatus
          archived={shelf.archived}
          failed={shelf.archivedFailed}
          /* An empty archive over an empty shelf is said once, below. */
          saysEmpty={(articles?.length ?? 0) > 0}
        />
      )}

      {/* Between the controls and the count, so the count is visibly the
          result of everything above it. Only once there is a shelf and an
          answer: a failed request draws nothing (useShelfTerms.ts), and
          while one is out a spinner holds the row's place. */}
      {/* The reader's own tags, above the topics — ShelfTagFilter.tsx. */}
      {total > 0 && (
        <ShelfTagFilter
          facets={tagList}
          counts={tagCounts}
          selected={tagsChosen}
          onToggle={toggleTag}
          onClear={() => pushView(() => void setTags(null))}
        />
      )}
      {total > 0 && !terms.data && terms.loading && <ShelfTermsLoading articleCount={total} />}
      {total > 0 && terms.data && (
        <ShelfTerms
          data={terms.data}
          counts={counts}
          selected={topics}
          onToggle={toggleTopic}
          onClear={() => pushView(() => void setTopics(null))}
          entryOf={shelfTopics.entryOf}
          inScope={shelfTopics.inScope}
          archived={archivedOn}
          articleTopics={topicsOfArticles}
        />
      )}

      {/* The same count the chips use: a chosen chip's number is this line's
          first number (shelf-narrow.ts § topicCounts). With the archive in
          scope, both halves are counted and each is named. */}
      {narrowed && (
        <p className="tw:mb-3 tw:mt-0 tw:text-xs tw:text-muted-foreground">
          {showing} of {total} {total === 1 ? "article" : "articles"}
          {inArchive && ` (${showing - archivedShowing} active + ${archivedShowing} archived)`}
        </p>
      )}

      {/* Silent until the wait is worth mentioning — on a warm shelf this fetch
          is over well before that, and a line that flashes up and away reads as
          a fault. After that, say what is being fetched. See useSlow.ts, which
          owns the threshold. */}
      {!error && articles === null && slow && (
        <p className="tw:text-sm tw:text-muted-foreground">Reading the shelf…</p>
      )}
      {/* From the combined scope (Sol R2): with Archived on and the archive
          loaded, a shelf of archived articles is not "nothing on the shelf".
          While the archive is still loading, it is not said at all — it may
          be about to be untrue. */}
      {articles !== null && total === 0 && (!archivedOn || inArchive !== null) && (
        <EmptyShelf
          archivedOn={archivedOn}
          publicOn={publicOn}
          onPublic={() => pushView(() => void setPublicOn(true))}
        />
      )}
      {showing === 0 && total > 0 && (
        <p className="tw:text-sm tw:text-muted-foreground">
          {nothingLeft(query, show, topics.length > 0, tagsChosen.length > 0)}
        </p>
      )}

      {/* One list, two renderers. The sort, the filter and the search are all
          resolved above this line, so neither view can disagree with the other
          about what is on the shelf or what order it is in — see
          ShelfControls.tsx. */}
      {/* **The first few, and a button for the rest.** Greg, 2026-09-06:

          > the table should by default only show the top 50? or so Articles,
          > with a button at the bottom to show all. Eventually we might consider
          > paging, but probably that's overkill for now

          He asked for the table and then asked for the cards too, so both are
          capped — at different numbers, for the reason under `SHELF_ROW_CAP`.

          Sliced **here**, after both `sinkLast` passes, rather than inside
          `DataTable`: the cap is caller policy, which is the same reason
          `DataTable` takes its rows as a prop rather than reading them off the
          table. It also could not carry the label — `DataTable`'s other consumer
          is /admin's list of accounts (AdminPage.tsx), and "Show all 213
          articles" is not a sentence a shared component can write.

          Slicing before the sort would cap the wrong fifty.

          **The button is outside the view switch, drawn once.** It was inside
          the table branch while the table was the only capped view, and the
          obvious way to cap the cards was to write it a second time next to the
          `<ul>` — two copies of one rule, which is the thing lib/row-cap.ts
          exists to stop happening. Here the branch chooses a renderer and
          nothing else, so a capped view without its button is not a shape this
          JSX can take. */}
      {sorted.length > 0 && (
        <ArticleTopicsContext.Provider value={topicsOfArticles}>
        <TopicsExpectedContext.Provider value={expectTopics}>
          {view === "table" ? (
            /* **One `TooltipGroup` for the whole table**, so running the pointer
               down the titles opens each row card instantly after the first,
               and so the row's action buttons join it rather than nesting a
               group of their own (`Actions` § `inTooltipGroup`) — two groups
               could hold a title's card and an action's open together. The
               actions' own delays, which they had before. Plan 260928a. */
            <TooltipGroup delay={{ open: 240, close: 90 }} timeoutMs={400}>
              <DataTable table={table} rows={capped.shown} caption="Your articles" />
            </TooltipGroup>
          ) : (
            <ul className="tw:m-0 tw:flex tw:list-none tw:flex-col tw:gap-3 tw:p-0">
              {capped.shown.map((row) => (
                <li key={row.id}>
                  <ShelfCard
                    entry={row.original}
                    shelf={shelf}
                    note={note(row.original, now)}
                    archivedShown={archivedOn}
                    topics={<ShelfRowTopics slug={row.original.slug} className="tw:mt-1.5" />}
                    readThis={
                      row.original.processing === "minimal" ? (
                        <ReadThisButton slug={row.original.slug} />
                      ) : undefined
                    }
                  />
                </li>
              ))}
            </ul>
          )}
          {/* Drawn exactly when `revealTotal` is a number, and that number is
              the only count it can print — see lib/row-cap.ts on why the slice
              and the button come from one call rather than two conditions that
              agree until somebody edits one of them. Note it is a sibling of
              the `<ul>` rather than a child: a bare `<button>` inside a list is
              invalid HTML, and the list has semantics a screen reader reads. */}
          {capped.revealTotal !== null && (
            <ShowAllRows total={capped.revealTotal} onShowAll={() => setExpanded(true)} />
          )}
        </TopicsExpectedContext.Provider>
        </ArticleTopicsContext.Provider>
      )}

      {/* The passages obey the Unread chip too. Without that, turning Unread on
          and searching for something only an opened article contains printed
          "No unopened article matches …" and then listed passages from that
          very article — two answers to one question, on one screen. The hidden
          ones are counted rather than silently dropped, because "it is in
          something you have already read" is the useful half of that answer. */}
      {searching && <Passages state={passages} query={query} only={unread} archived={archivedOn} />}

      {/* **Right after the search's answer: what it left out, how much, and the
          button.** Greg, spya-s9fhmw. ShelfSearchAlso.tsx; plan 261002b § Part D. */}
      {searching && (!archivedOn || !publicOn) && (
        <ShelfSearchAlso
          query={query}
          archivedOn={archivedOn}
          publicOn={publicOn}
          archived={archivedTally}
          listing={publicListing}
          listingReady={shelf.liveArticlesLoaded}
          ownSlugs={ownSlugs}
          narrowedElsewhere={show === "unread" || topics.length > 0}
          onArchived={() => pushView(() => void setArchivedOn(true))}
          onPublic={() => pushView(() => void setPublicOn(true))}
        />
      )}

      {/* After your own articles and their passages, because it is the
          further reach: the same search box, someone else's shelf. */}
      {/* A saved shelf copy is deliberately enough to paint the owner's cards,
          but not enough to call a public article somebody else's: it may be
          missing an article added since the last visit. Wait for the live
          owner list before starting the anonymous public read. */}
      <ShelfPublicSection
        listing={publicListing}
        enabled={publicOn}
        ownerLoaded={articles !== null}
        ownerReady={shelf.liveArticlesLoaded}
        query={query}
        ownSlugs={ownSlugs}
        narrowedElsewhere={show === "unread" || topics.length > 0}
      />

      {/* **No "Show archived" here any more** (plan 260929a): it was a
          disclosure at the foot of the shelf, with its own second list, and
          is the Archived chip beside Unread now — ShelfControls.tsx. */}

      {/* Greg's own example of a signed-in page that should carry one
          (2026-09-03). The shelf has a bottom, and it is where a reader who has
          been away comes back to — so it is where the policy and the feature
          list stay reachable long after the landing page stopped being shown to
          them.

          **`here` because this page is App.tsx's fallback**, exactly as the
          landing page is signed out: a non-administrator at `/admin` gets the
          shelf. Without this the row offered that reader a Home link to the
          shelf they were already looking at. GPT Sol, 2026-09-03.

          Every unrecognised address landed here too until later the same day,
          when they got a page of their own — NotFoundPage.tsx. One address
          still needs this, which is one more than none. SiteFooter.tsx §
          `here`. */}
      <SiteFooter here="library" />
    </main>
  );
}

/**
 * **An empty shelf, with somewhere to go from it.**
 *
 * > if the user has no articles in their shelf, we probably actually want to,
 * > as well as saying you have no articles yet, you know, upload them, you know,
 * > see above or whatever with a link that points them to the top. … So just
 * > kind of provide a bit more help to new users that don't yet have anything
 * > on their shelf
 * >
 * > — Greg, 2026-10-01 (spya-yy5x66)
 *
 * Two ways on: the add box, as a link that takes you to it and puts the cursor
 * in it, and the public shelf, as a button that turns Include public on — the
 * same act as the chip, so it lands in the URL and Back undoes it. With Include
 * public already on, the second is not offered.
 */
function EmptyShelf({
  archivedOn,
  publicOn,
  onPublic,
}: {
  archivedOn: boolean;
  publicOn: boolean;
  onPublic: () => void;
}) {
  return (
    <p className="tw:text-sm tw:text-muted-foreground">
      {archivedOn ? "Nothing on the shelf, and nothing archived." : "Nothing on your shelf yet."}{" "}
      <a
        href={`#${ADD_URL_ID}`}
        onClick={(e) => {
          /* Focus does the scrolling, and it is the half a fragment link alone
             would not do: the reader lands *in* the box, ready to paste. */
          const box = document.getElementById(ADD_URL_ID);
          if (!box) return;
          e.preventDefault();
          box.focus();
          box.scrollIntoView({ block: "center" });
        }}
        className="tw:text-highlight-text tw:underline"
      >
        Paste a link to an article in the box at the top
      </a>{" "}
      and it'll be here in a minute or two.
      {!publicOn && (
        <>
          {" "}
          Or{" "}
          <button
            type="button"
            onClick={onPublic}
            className="tw:cursor-pointer tw:border-0 tw:bg-transparent tw:p-0 tw:text-sm tw:text-highlight-text tw:underline"
          >
            browse what other readers have shared
          </button>
          .
        </>
      )}
    </p>
  );
}

/** The add box's input — AddArticle.tsx. */
const ADD_URL_ID = "add-url";

/**
 * Why nothing is on screen.
 *
 * A shelf with articles on it and nothing matching is a different thing from an
 * empty shelf, and it has to say **which** of the two narrowings emptied it —
 * otherwise pressing Unread on a shelf you have read all of looks like the
 * search box has broken.
 */
function nothingLeft(query: string, show: ShelfFilter, topics: boolean, tags: boolean): string {
  const q = query.trim();
  /* Named first when it is on: of the narrowings, a topic or tag chosen from a
     link is the one a reader is least likely to remember is there. */
  if (topics || tags) {
    if (q || show === "unread") return "Nothing on the shelf matches everything chosen above.";
    const what = topics && tags ? "tag and topic" : tags ? "tag" : "topic";
    return `No article on the shelf has every ${what} chosen.`;
  }
  if (q && show === "unread") return `No unopened article matches “${q}”.`;
  if (q) return `No article's title, author or blurb matches “${q}”.`;
  return "You have opened all of them.";
}

/** Stable identity, and — see lib/DataTable.tsx — the tiebreak behind every sort. */
const slugOf = (entry: LibraryEntry) => entry.slug;

/** One frozen empty array, so a shelf that has not loaded does not rebuild the table each render. */
const EMPTY: LibraryEntry[] = [];

/** One deduplicated scope, preferring the newer archived-side server answer. */
function shelfScope(
  active: readonly LibraryEntry[] | null,
  archived: readonly LibraryEntry[],
  archivedOn: boolean,
): LibraryEntry[] | null {
  if (!active || !archivedOn) return active ? [...active] : null;
  /* `useShelf` normally prevents the same slug reaching both halves. Resolve
     it here too so a transient stale response can never create duplicate
     TanStack row ids; the archived copy carries the newer mutation state. */
  const merged = new Map(active.map((entry) => [entry.slug, entry]));
  for (const entry of archived) merged.set(entry.slug, entry);
  return [...merged.values()];
}

/**
 * How many rows the table draws before it asks.
 *
 * Fifty is the middle of what real products pick — GitHub's API pages at 30,
 * Gmail at 50, Notion offers 10/25/50/100 — and it is a reveal rather than
 * pagination on purpose. NN/g's own framing is that infinite scroll and its
 * relatives suit "homogeneous items with no particular task or goal", and hurt
 * anything you need to *find or return to*; a personal library is the second
 * kind, so the affordance that keeps the back button, the footer and a sense of
 * place is a button you press once.
 *
 * **Two numbers, because the cap is a page-height budget rather than a row
 * count.** A card is a title, a byline, a blurb and five buttons — call it four
 * table rows — so fifty of them is a page five times longer than the fifty rows
 * this cap exists to prevent, which would be the cap defeating its own purpose.
 * Twenty is roughly the same amount of page.
 *
 * Keyed by view rather than two loose constants: both numbers sit on one line,
 * there is no ternary at the call site, and the type refuses a view with no cap.
 *
 * The **fifty** is Greg's ("50? or so"); the **twenty** is Fable's, 2026-09-06,
 * and is the one to move first if this feels wrong.
 *
 * Nothing on screen says either number — `ShowAllRows` prints the *total*, which
 * is the same in both views — so switching views never changes a count. All the
 * reader sees is that a shelf of, say, thirty articles offers the button in
 * cards and not in the table, which is the cap working rather than a bug.
 */
const SHELF_ROW_CAP = { cards: 20, table: 50 } as const;

/**
 * **"Show all 213 articles"** — the count is in the label rather than in a
 * caption above it.
 *
 * Notion's "Load N more" is the one shape among the candidates that was verified
 * against a shipped product, and it is the more actionable of the two: a reader
 * who wants the rest presses the thing that says how many the rest are. A
 * separate "showing 50 of 213" line would also be the *second* count on this
 * page — `narrowed` above already prints one whenever the search box or the
 * Unread chip is hiding something, and two counts that mean different things,
 * one above the table and one below it, is a worse page than either.
 *
 * Full width and quiet: it is the foot of the list, not a call to action.
 */
function ShowAllRows({ total, onShowAll }: { total: number; onShowAll: () => void }) {
  return (
    <button
      type="button"
      onClick={onShowAll}
      className="tw:mt-2 tw:w-full tw:rounded-lg tw:border tw:border-border tw:bg-transparent tw:px-4 tw:py-2 tw:text-xs tw:text-muted-foreground tw:transition-colors tw:hover:border-highlight/50 tw:hover:bg-highlight/5 tw:hover:text-foreground"
    >
      Show all {total.toLocaleString()} articles
    </button>
  );
}

/* ------------------------------------------------------------- searching -- */

/* The cards' own matcher — `filterEntries` — lives in shelf-narrow.ts since
   2026-09-28, so the archived list is searched by the same rule. */

/**
 * **Does the search box take the focus as the shelf arrives?**
 *
 * > When I open the logged-in Spideryarn homepage with the shelf, let's put
 * > the focus by default on the search box.
 * >
 * > — Greg, 2026-09-29
 *
 * Yes, unless one of four readers would be worse off for it:
 *
 *  - **a finger is the primary pointer** — the on-screen keyboard would cover
 *    half the shelf they came to look at. `pointer`, not `any-pointer`, so a
 *    touchscreen laptop with a trackpad still gets it; and `media()` answers
 *    `false` where it cannot tell, so an unknown pointer gets it too;
 *  - **the page arrived with a query in it** — they are reading results, and a
 *    stray key would change their query;
 *  - **something else already has the focus** — the shelf takes it from nobody;
 *  - **the box is not wholly on screen** — scroll restoration is manual
 *    (main.tsx), so Back from far down an article can mount the shelf scrolled,
 *    and typing into a box you cannot see is worse than no focus. Scrolling to
 *    it would yank the page instead.
 *
 * docs/plans/260929g-shelf-search-focus-and-metadata-chord.md § Part A.
 */
function takesFocusOnArrival(input: HTMLInputElement, arrivingQuery: string): boolean {
  if (media("(pointer: coarse)") || arrivingQuery !== "") return false;
  const active = document.activeElement;
  if (active !== null && active !== document.body) return false;
  const box = input.getBoundingClientRect();
  return (
    box.top >= 0 &&
    box.right <= layoutViewportWidth() &&
    box.bottom <= window.innerHeight &&
    box.left >= 0
  );
}

function SearchBox({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const input = useRef<HTMLInputElement>(null);
  /* **Decided once, on mount**, from the query the page arrived with: clearing
     a query must not re-grab the focus, and neither must the shelf's data
     landing. Back from an article remounts the shelf, so it asks again — that
     is arriving too. `preventScroll`, so arriving never moves the page. */
  const arrivingQuery = useRef(value);
  useEffect(() => {
    const el = input.current;
    if (el && takesFocusOnArrival(el, arrivingQuery.current)) el.focus({ preventScroll: true });
  }, []);
  /* **Was the cross pressed with a finger or pen?** Read at the `pointerdown`,
     never off the click: since iOS 18.2 a finger's click can say `mouse`
     (docs/project/touch.md § The spine). The click still tells us when no
     pointer made it, so an abandoned touch cannot poison a later keyboard,
     voice or assistive-technology activation. */
  const fingerOrPenOnCross = useRef(false);
  return (
    <div className="tw:mb-4">
      <div className="tw:relative">
        <Search
          size={15}
          className="tw:pointer-events-none tw:absolute tw:left-3 tw:top-1/2 tw:-translate-y-1/2 tw:text-muted-foreground"
        />
        <input
          ref={input}
          type="search"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          /* The shelf filters as you type, so Enter has no search left to run —
             what it does is put the phone's keyboard away, which is what the
             reader pressed it for. Without the blur the key would be a promise
             with nothing behind it. */
          enterKeyHint="search"
          onKeyDown={(e) => {
            if (e.key === "Escape" && value !== "") e.stopPropagation();
            /* A key an input method is using is not ours: its Enter accepts a
               candidate and its Escape dismisses the list. A `type="search"`
               box is also emptied by the browser itself on Escape (measured in
               Chrome, 2026-10-07), so that default is cancelled. */
            if (isImeComposing(e)) {
              if (e.key === "Escape") e.preventDefault();
              return;
            }
            if (e.key === "Enter") {
              e.preventDefault();
              e.currentTarget.blur();
            } else if (e.key === "Escape" && value !== "") {
              /* Only when there is something to clear, so an Escape in an empty
                 box still reaches whatever else on the page listens for it —
                 the same rule as PageContents.tsx's box. */
              e.preventDefault();
              onChange("");
            }
          }}
          placeholder="Search titles, authors, and article text"
          aria-label="Search the library"
          /* A ring as well as a border colour on focus. A 1px border changing
             from grey to orange is about one pixel's worth of colour on a
             near-black page, which is not enough to find the box you have just
             tabbed into — and this input suppresses the browser's own ring
             with `outline-none`, so nothing else was drawing one. Same
             treatment on the URL box in AddArticle.tsx. */
          /* `own-clear` hides the browser's cross (styles/close.css): ours is
             below, and two were being drawn whenever the box had the focus.
             The right padding is fixed in px, like the cross: `pr-11` would
             shrink to 33px at the supported 12px root and let text under its
             40px finger target. */
          className="own-clear voice-reader tw:w-full tw:rounded-lg tw:border tw:border-border tw:bg-card tw:py-2 tw:pl-9 tw:pr-[44px] tw:text-sm tw:text-foreground tw:any-pointer-coarse:text-base tw:transition-colors tw:outline-none tw:placeholder:text-muted-foreground tw:focus:border-highlight-text tw:focus:ring-2 tw:focus:ring-highlight-text/25"
        />
        {value && (
          /* **The house cross** — its size is styles/close.css § .close-x, so
             **no `tw:size-*` here**: the utilities layer comes after the app's
             CSS and would win, quietly putting back the 28px box and 14px grey
             glyph this change replaces (GPT Sol, plan review).
             docs/plans/261004f-shelf-search-clear-cross-that-can-be-seen.md. */
          <button
            type="button"
            onPointerDown={(e) => {
              fingerOrPenOnCross.current = e.pointerType === "touch" || e.pointerType === "pen";
            }}
            onPointerCancel={() => {
              fingerOrPenOnCross.current = false;
            }}
            onClick={(e) => {
              onChange("");
              /* The cursor goes back in the box, ready for the next search —
                 but not after a finger or pen, where it could throw the
                 on-screen keyboard up over the shelf the reader has just
                 asked to see. */
              const clickPointer = (e.nativeEvent as Partial<PointerEvent>).pointerType;
              const noPointer = clickPointer === "" || (clickPointer === undefined && e.detail < 1);
              if (noPointer || !fingerOrPenOnCross.current) {
                input.current?.focus({ preventScroll: true });
              }
              fingerOrPenOnCross.current = false;
            }}
            aria-label="Clear the search"
            className="close-x tw:absolute tw:right-[6px] tw:top-1/2 tw:-translate-y-1/2 tw:text-foreground tw:transition-colors tw:hover:bg-highlight/10"
          >
            <X size={18} />
          </button>
        )}
      </div>
    </div>
  );
}

/**
 * The passages, under the cards.
 *
 * Under rather than beside, and after rather than before, because the cards are
 * the answer to "which of my articles is this?" and the passages are the answer
 * to "where in them?". The first question is the commoner one and the free one.
 */
function Passages({
  state,
  query,
  only,
  archived,
}: {
  state: ReturnType<typeof useLibrarySearch>;
  query: string;
  /** The Include archived chip — what the search was asked, and what "nothing" means. */
  archived: boolean;
  /**
   * The slugs the Unread chip is letting through, or `null` for "everything".
   *
   * Narrowing happens **here rather than in the request**, and that has a cost
   * worth stating: the server caps the list before we see it, so a query whose
   * best hits are all in articles you have read can come back with nothing left
   * for this to show even though matches exist. That is the same trap
   * `excludeSlug` exists to avoid for chat's `search_library`
   * (docs/project/chat-tools.md). It is acceptable here and not there because
   * the reader can see the chip they pressed, and the line below says how many
   * were hidden — a caller reporting "found nothing" cannot do either.
   */
  only: Set<string> | null;
}) {
  if (state.error) {
    return (
      <p className="tw:mt-8 tw:text-sm tw:text-muted-foreground">
        Couldn't search the text of the articles: {state.error}
      </p>
    );
  }
  if (state.searching && state.hits.length === 0) {
    return <p className="tw:mt-8 tw:text-sm tw:text-muted-foreground">Searching the text…</p>;
  }
  if (!state.asked) return null;
  /* Results are shown only for the query they are the answer to. Without this
     the previous query's passages sit on screen while the next request runs,
     marked and linked with the NEW query — passages that do not contain what
     the reader typed, presented as though they do. */
  if (state.resultsQuery !== query.trim() || state.resultsArchived !== archived) return null;
  if (state.hits.length === 0) {
    return (
      <p className="tw:mt-8 tw:text-sm tw:text-muted-foreground">
        Nothing in the articles' text matches “{query.trim()}”.
        {/* That the archive was not searched used to be said here, as a
            sentence (SPIDERYARN-READING2-72). It is the line straight after
            now, with a count and a button — ShelfSearchAlso.tsx, spya-s9fhmw. */}
      </p>
    );
  }

  const hits = only ? state.hits.filter((h) => only.has(h.slug)) : state.hits;
  const hidden = state.hits.length - hits.length;
  /* Counted here rather than read from `state.articles`, which is the server's
     count over the hits it sent (`new Set(hits.map(h => h.slug)).size` in
     routes.ts — the same expression). It has to be the count of what is *shown*
     once the Unread chip can remove some, and the two agree exactly when
     nothing is removed. */
  const articles = new Set(hits.map((h) => h.slug)).size;

  /* Counted, never silently dropped: "it is in something you have already read"
     is the useful half of the answer, and a list that just came up empty with
     no explanation reads as a broken search. */
  const alsoIn = hidden > 0 && (
    <p className="tw:mt-2 tw:mb-0 tw:text-xs tw:text-muted-foreground">
      {hidden} more {hidden === 1 ? "passage is" : "passages are"} in articles you have already
      opened.
    </p>
  );

  if (hits.length === 0) {
    return (
      <section className="tw:mt-8">
        <p className="tw:m-0 tw:text-sm tw:text-muted-foreground">
          Nothing in an unopened article's text matches “{query.trim()}”.
        </p>
        {alsoIn}
      </section>
    );
  }

  return (
    <section className="tw:mt-8">
      <h2 className="tw:m-0 tw:mb-3 tw:text-xs tw:font-medium tw:tracking-wide tw:text-muted-foreground tw:uppercase">
        {hits.length} {hits.length === 1 ? "passage" : "passages"} in {articles}{" "}
        {articles === 1 ? "article" : "articles"}
        {/* Said out loud rather than silently truncated: a capped list that does
            not admit it reads as "that is everything". */}
        {state.capped && <span className="tw:ml-1 tw:normal-case">(showing the best)</span>}
      </h2>
      <ul className="tw:m-0 tw:flex tw:list-none tw:flex-col tw:gap-2 tw:p-0">
        {hits.map((hit) => (
          <li key={`${hit.slug}/${hit.blockId}`}>
            <Passage hit={hit} query={query} />
          </li>
        ))}
      </ul>
      {alsoIn}
    </section>
  );
}

/** How much of the paragraph to show. Wide enough to judge, short enough to skim. */
const SNIPPET_CHARS = 200;

function Passage({ hit, query }: { hit: LibraryHit; query: string }) {
  /* The four parameters this link must carry, and why dropping any one of them
     fails silently, are documented on `libraryHitHref` — a pure function in a
     module of its own precisely so that rule can be tested. It lost one of the
     four while it lived inline here, and the symptom was a link whose every
     present parameter was correct and which highlighted nothing. */
  const href = libraryHitHref(hit, query);

  return (
    <Link
      href={href}
      className="tw:block tw:rounded-md tw:border tw:border-border tw:bg-card tw:px-4 tw:py-3 tw:no-underline tw:hover:border-highlight/60"
    >
      <span className="tw:flex tw:flex-wrap tw:items-center tw:gap-2 tw:text-xs tw:text-muted-foreground">
        {/* The author's title, or the reader's rename (voice.ts). `undefined`
            on a hit from before the flag, which `articleTitleVoice` draws as ours. */}
        <span className={voiceClass(articleTitleVoice(hit.titleOverridden))}>{hit.title}</span>
        {/* Only ever set with Include archived on. Marked as the card is, so a
            passage that opens an article you archived is not a ghost. */}
        {hit.archived && <ArchivedMark />}
      </span>
      <span
        className={withVoice("tw:mt-1 tw:block tw:text-[0.95rem] tw:leading-relaxed tw:text-foreground", "author")}
      >
        {marked(hit.text, query)}
      </span>
    </Link>
  );
}

/**
 * A window of the paragraph around the first match, with the match in bold.
 *
 * The cutting and the marking happen here rather than on the server because the
 * two stores would do them differently — Postgres knows which *stems* matched,
 * not which characters — and two flavours of highlighting to reconcile is worse
 * than one that occasionally shows the start of the paragraph instead. See
 * `LibraryHit.text`.
 *
 * A stemmed hit is exactly that case: Postgres can match "qualias" for a search
 * for "qualia", and this will not find those letters. It falls back to the
 * opening of the paragraph, which is honest and readable rather than empty.
 */
function marked(text: string, query: string) {
  const terms = queryTerms(query);
  const { folded, starts, ends } = foldWithMap(text);

  let at = -1;
  let length = 0;
  for (const term of terms) {
    const i = folded.indexOf(term);
    if (i !== -1 && (at === -1 || i < at)) {
      at = i;
      length = term.length;
    }
  }

  // Nothing to point at — a stemmed match, or a term shorter than two
  // characters. Show the opening of the paragraph, which is honest and
  // readable rather than empty.
  if (at === -1) {
    const head = text.slice(0, SNIPPET_CHARS);
    return head.length < text.length ? `${head}…` : head;
  }

  /* Every offset is translated before it touches `text`, so the snippet carries
     the article's own punctuation — and the END comes from `ends`, which is the
     exclusive end of the source character the match finished inside. See
     `foldWithMap`. */
  const start = starts[at] ?? 0;
  const end = ends[at + length - 1] ?? text.length;
  const want = Math.max(0, SNIPPET_CHARS - (end - start));
  const from = Math.max(0, start - Math.floor(want / 2));
  const to = Math.min(text.length, end + (want - (start - from)));

  return (
    <>
      {from > 0 && "…"}
      {text.slice(from, start)}
      <strong className="tw:font-semibold tw:text-highlight-text">{text.slice(start, end)}</strong>
      {text.slice(end, to)}
      {to < text.length && "…"}
    </>
  );
}

/* ------------------------------------------------------------- archived --- */

/**
 * **What the archive is doing, while Include archived is on** — one quiet
 * line under the controls, and only when there is something to say.
 *
 * The archived articles themselves are not drawn here any more. Until plan
 * 260929a they were a second list behind a "Show archived" disclosure at the
 * foot of the shelf; since Greg's report 4V they join the shelf's one list, so
 * the sort, the search, Unread and the topics apply to them (the `scope` memo
 * in `Library`). What is left for this line is the time before that list
 * exists, and the case where it came back empty.
 *
 * Why an archive has to be reachable at all is unchanged: without it Archive is
 * **permanent from the interface** — the Undo strip is gone after nine seconds
 * — and Greg chose "archive, with an Undo" over a real delete precisely so that
 * nothing is destroyed. docs/project/library.md § Archive, and Undo is the
 * confirmation.
 *
 * **The words said "deleted" until 2026-09-04**, over an act that has always
 * archived; the same section has the report that changed them.
 */
function ArchiveStatus({
  archived,
  failed,
  saysEmpty,
}: {
  /** `shelf.archived`: `null` until it has loaded. */
  archived: LibraryEntry[] | null;
  /** The last load failed; the reason is in the shelf's action error above. */
  failed: boolean;
  /** Whether "Nothing archived." is this line's to say. */
  saysEmpty: boolean;
}) {
  let text: string | null = null;
  if (archived === null) {
    text = failed
      ? "Couldn't load the archived articles. Turn Include archived off and on to try again."
      : "Loading archived…";
  } else if (archived.length === 0 && saysEmpty) {
    text = "Nothing archived.";
  }
  if (!text) return null;
  /* `status`, so a screen reader hears the load finish or fail when it gets
     to it — the same politeness as the Undo strip below. */
  return (
    <p role="status" className="tw:mb-3 tw:mt-0 tw:text-xs tw:text-muted-foreground">
      {text}
    </p>
  );
}

/* ----------------------------------------------------------------- undo --- */

function UndoStrip({ title, onUndo }: { title: string; onUndo: () => void }) {
  return (
    <div
      /* `status`, not `alert`: a screen reader should hear this when it gets to
         it rather than have the current sentence interrupted. Archiving was
         the reader's own act, so it is a confirmation, not an emergency. */
      role="status"
      className="tw:mb-3 tw:flex tw:items-center tw:gap-3 tw:rounded-md tw:border tw:border-border tw:bg-card tw:px-4 tw:py-2 tw:text-sm tw:text-foreground"
    >
      <span className="tw:min-w-0 tw:flex-1 tw:truncate">Archived “{title}”</span>
      <button
        type="button"
        onClick={onUndo}
        className="tw:inline-flex tw:h-7 tw:shrink-0 tw:items-center tw:gap-1.5 tw:rounded-md tw:px-2.5 tw:text-xs tw:text-highlight-text tw:transition-colors tw:hover:bg-highlight/10"
      >
        <Undo2 size={14} />
        Undo
      </button>
    </div>
  );
}

/* -------------------------------------------------------------- masthead --- */

/**
 * A sentence in a hover card, sized.
 *
 * `.tooltip` in styles.css paints the surface and nothing else — no size, no
 * colour — because every tooltip in the reading view carries classed content
 * that sets its own (`.where-card`, `.tip-search`, `.tip-soon`). This page is
 * Tailwind, so the sizing lives here in the same way `Note` does in
 * Metadata.tsx rather than as a sixth `.tip-*` rule in the stylesheet.
 *
 * `ink-soft` — the same colour `TipNote` in Tooltip.tsx uses, and for the same
 * reason. Both said `foreground/85` until 2026-09-05, because `--ink-soft` was
 * missing from the `@theme inline` bridge and `tw:text-ink-soft` compiled to
 * nothing at all; two people diagnosed that independently and each wrote a
 * comment about the workaround rather than three lines of fix
 * (docs/plans/260905f-…).
 */
function Tip({ children }: { children: ReactNode }) {
  return <span className="tw:block tw:text-xs tw:leading-relaxed tw:text-ink-soft">{children}</span>;
}

/**
 * **The spider and the name at the top of the shelf, which play the whole
 * wordmark set on a hover and on a tap.**
 *
 * > We don't seem to get the fun logo animations for the logo in the top left
 * > of the logged in homepage.
 * >
 * > — Greg, 2026-09-30, SPIDERYARN-READING2-6D
 *
 * **One host round both, since then.** From 2026-09-15 the hook sat on the
 * spider alone and the `<h1>` beside it was plain text, so pointing at the word
 * did nothing and only the spider's six animations could ever be drawn here —
 * `lettersDrawn` asks the host for a `.logo-letter` (logo-animation.ts §
 * pickLogoAnimation). The heading was kept out of the 2026-09-29 spread
 * (LogoGlyphs.tsx) deliberately: the letter moves were fixed pixels tuned for a
 * 13px word and read as half a gesture at 30px. They are measured in the word's
 * own size now (styles/logo-animations.css § `--logo-px`), which was the named
 * way to change that.
 * docs/plans/260930a-cmd-k-on-metadata-page-and-full-wordmark-animations-on-the-shelf.md.
 *
 * **The heading is still a heading**: `LogoLetters` puts ten spans inside it
 * with no whitespace between them, so its text, and its accessible name, is
 * still "Spideryarn". It keeps the heading's size; the letters share every
 * copy's face, weight, tracking and white, and Dawn turns them orange for a
 * moment and back, as it does the footer's.
 *
 * **A tap plays one here, where on the reading view it goes home**, because
 * here it does nothing else — `{ tap: true }`, decided on the click.
 *
 * **Not a `<button>`.** A tab stop whose only effect is a flourish is noise to a
 * keyboard or screen-reader reader, so the host adds nothing to the
 * accessibility tree; the spider is `alt=""` and hidden, for the reason
 * HomeLogo.tsx gives — the name is right beside it. `shelf-wordmark` carries the
 * long-press lines a `.logo` would (styles/dock.css).
 */
export function ShelfWordmark() {
  const anim = useLogoAnimation({ tap: true });
  return (
    <div
      className={`shelf-wordmark tw:flex tw:items-center tw:gap-2.5 ${anim.className}`}
      {...anim.handlers}
    >
      <span className="tw:inline-flex" aria-hidden="true">
        <LogoMark size={28} />
      </span>
      {/* A wrapper round the ten letters and nothing else, because the stagger
          is `:nth-child` over exactly those (LogoGlyphs.tsx). The `<h1>` is
          that wrapper. Its face, weight, tracking and colour are the letters'
          own, the same as every other copy (styles/tokens.css §
          .logo-letter); the size is the heading's. */}
      <h1 className="tw:text-3xl">
        <LogoLetters />
      </h1>
    </div>
  );
}
